module.exports = {
  filter1: require('./filter1'),
  filter2: require('./filter2'),
  filter3: require('./filter3'),
  filter4: require('./filter4'),
  filter5: require('./filter5'),
  filter6: require('./filter6'),
  filter7: require('./filter7'),
  filter8: require('./filter8'),
  filter9: require('./filter9'),
  filter10: require('./filter10'),
  filter11: require('./filter11'),
  filter12: require('./filter12'),
  filter13: require('./filter13'),
  filter14: require('./filter14'),
  filter15: require('./filter15'),
  filter16: require('./filter16'),
  filter17: require('./filter17'),
  filter18: require('./filter18'),
  albumswithvsandmeets: require('./albumswithvsandmeets'),
  correctlanguagesetatalbumlevel: require('./correctlanguagesetatalbumlevel'),
  nazipropaganda: require('./nazipropaganda'),
  duplicatesthreshold: require('./duplicatesthreshold')
}
