let config = require('config')

// Below are genre info fetched from "Music, Music Video, and Ringtone Genre Codes 5.3":
// https://itunespartner.apple.com/assets/downloads/Music_MusicVideo_Ringtone_Genre_Codes.xls

const musicGenrePaths = [
  'Music',
  'Music|Alternative',
  'Music|Alternative|Chinese Alt',
  'Music|Alternative|College Rock',
  'Music|Alternative|EMO',
  'Music|Alternative|Goth Rock',
  'Music|Alternative|Grunge',
  'Music|Alternative|Indie Pop',
  'Music|Alternative|Indie Rock',
  'Music|Alternative|Korean Indie',
  'Music|Alternative|New Wave',
  'Music|Alternative|Pop Punk',
  'Music|Alternative|Punk',
  'Music|Anime',
  'Music|Arabic',
  'Music|Arabic|Arabic Pop',
  'Music|Arabic|Islamic',
  'Music|Arabic|Khaleeji',
  'Music|Arabic|North African',
  'Music|Blues',
  'Music|Blues|Acoustic Blues',
  'Music|Blues|Chicago Blues',
  'Music|Blues|Classic Blues',
  'Music|Blues|Contemporary Blues',
  'Music|Blues|Country Blues',
  'Music|Blues|Delta Blues',
  'Music|Blues|Electric Blues',
  'Music|Brazilian',
  'Music|Brazilian|Axé',
  'Music|Brazilian|Baile Funk',
  'Music|Brazilian|Bossa Nova',
  'Music|Brazilian|Choro',
  'Music|Brazilian|Forró',
  'Music|Brazilian|Frevo',
  'Music|Brazilian|MPB',
  'Music|Brazilian|Pagode',
  'Music|Brazilian|Samba',
  'Music|Brazilian|Sertanejo',
  "Music|Children's Music",
  "Music|Children's Music|Lullabies",
  "Music|Children's Music|Sing-Along",
  "Music|Children's Music|Stories",
  'Music|Chinese',
  'Music|Chinese|Chinese Classical',
  'Music|Chinese|Chinese Flute',
  'Music|Chinese|Chinese Opera',
  'Music|Chinese|Chinese Orchestral',
  'Music|Chinese|Chinese Regional Folk',
  'Music|Chinese|Chinese Strings',
  'Music|Chinese|Taiwanese Folk',
  'Music|Chinese|Tibetan Native Music',
  'Music|Christian & Gospel',
  'Music|Christian & Gospel|CCM',
  'Music|Christian & Gospel|Christian Metal',
  'Music|Christian & Gospel|Christian Pop',
  'Music|Christian & Gospel|Christian Rap',
  'Music|Christian & Gospel|Christian Rock',
  'Music|Christian & Gospel|Classic Christian',
  'Music|Christian & Gospel|Contemporary Gospel',
  'Music|Christian & Gospel|Gospel',
  'Music|Christian & Gospel|Praise & Worship',
  'Music|Christian & Gospel|Southern Gospel',
  'Music|Christian & Gospel|Traditional Gospel',
  'Music|Classical',
  'Music|Classical|Art Song',
  'Music|Classical|Avant-Garde',
  'Music|Classical|Baroque Era',
  'Music|Classical|Brass & Woodwinds',
  'Music|Classical|Cantata',
  'Music|Classical|Cello',
  'Music|Classical|Chamber Music',
  'Music|Classical|Chant',
  'Music|Classical|Choral',
  'Music|Classical|Classical Crossover',
  'Music|Classical|Classical Era',
  'Music|Classical|Contemporary Era',
  'Music|Classical|Electronic',
  'Music|Classical|Guitar',
  'Music|Classical|Impressionist',
  'Music|Classical|Medieval Era',
  'Music|Classical|Minimalism',
  'Music|Classical|Modern Era',
  'Music|Classical|Opera',
  'Music|Classical|Oratorio',
  'Music|Classical|Orchestral',
  'Music|Classical|Percussion',
  'Music|Classical|Piano',
  'Music|Classical|Renaissance',
  'Music|Classical|Romantic Era',
  'Music|Classical|Sacred',
  'Music|Classical|Solo Instrumental',
  'Music|Classical|Violin',
  'Music|Comedy',
  'Music|Comedy|Novelty',
  'Music|Comedy|Standup Comedy',
  'Music|Country',
  'Music|Country|Alternative Country',
  'Music|Country|Americana',
  'Music|Country|Bluegrass',
  'Music|Country|Contemporary Bluegrass',
  'Music|Country|Contemporary Country',
  'Music|Country|Country Gospel',
  'Music|Country|Honky Tonk',
  'Music|Country|Outlaw Country',
  'Music|Country|Thai Country',
  'Music|Country|Traditional Bluegrass',
  'Music|Country|Traditional Country',
  'Music|Country|Urban Cowboy',
  'Music|Cuban',
  'Music|Cuban|Bolero',
  'Music|Cuban|Chachacha',
  'Music|Cuban|Guajira',
  'Music|Cuban|Guaracha',
  'Music|Cuban|Mambo',
  'Music|Cuban|Son',
  'Music|Cuban|Timba',
  'Music|Dance',
  'Music|Dance|Breakbeat',
  'Music|Dance|Garage',
  'Music|Dance|Hardcore',
  'Music|Dance|House',
  "Music|Dance|Jungle/Drum'n'bass",
  'Music|Dance|Techno',
  'Music|Dance|Trance',
  'Music|Disney',
  'Music|Easy Listening',
  'Music|Easy Listening|Lounge',
  'Music|Easy Listening|Swing',
  'Music|Electronic',
  'Music|Electronic|Ambient',
  'Music|Electronic|Bass',
  'Music|Electronic|Downtempo',
  'Music|Electronic|Dubstep',
  'Music|Electronic|Electronica',
  'Music|Electronic|IDM/Experimental',
  'Music|Electronic|Industrial',
  'Music|Enka',
  'Music|Fitness & Workout',
  'Music|Folk',
  'Music|French Pop',
  'Music|German Folk',
  'Music|German Pop',
  'Music|Hip Hop/Rap',
  'Music|Hip Hop/Rap|Alternative Rap',
  'Music|Hip Hop/Rap|Chinese Hip-Hop',
  'Music|Hip Hop/Rap|Dirty South',
  'Music|Hip Hop/Rap|East Coast Rap',
  'Music|Hip Hop/Rap|Gangsta Rap',
  'Music|Hip Hop/Rap|Hardcore Rap',
  'Music|Hip Hop/Rap|Hip-Hop',
  'Music|Hip Hop/Rap|Korean Hip-Hop',
  'Music|Hip Hop/Rap|Latin Rap',
  'Music|Hip Hop/Rap|Old School Rap',
  'Music|Hip Hop/Rap|Rap',
  'Music|Hip Hop/Rap|UK Hip Hop',
  'Music|Hip Hop/Rap|Underground Rap',
  'Music|Hip Hop/Rap|West Coast Rap',
  'Music|Holiday',
  'Music|Holiday|Chanukah',
  'Music|Holiday|Christmas',
  "Music|Holiday|Christmas: Children's",
  'Music|Holiday|Christmas: Classic',
  'Music|Holiday|Christmas: Classical',
  'Music|Holiday|Christmas: Jazz',
  'Music|Holiday|Christmas: Modern',
  'Music|Holiday|Christmas: Pop',
  'Music|Holiday|Christmas: R&B',
  'Music|Holiday|Christmas: Religious',
  'Music|Holiday|Christmas: Rock',
  'Music|Holiday|Easter',
  'Music|Holiday|Halloween',
  'Music|Holiday|Thanksgiving',
  'Music|Indian',
  'Music|Indian|Bollywood',
  'Music|Indian|Devotional & Spiritual',
  'Music|Indian|Ghazals',
  'Music|Indian|Indian Classical',
  'Music|Indian|Indian Folk',
  'Music|Indian|Indian Pop',
  'Music|Indian|Punjabi Pop',
  'Music|Indian|Rabindra Sangeet',
  'Music|Indian|Regional Indian',
  'Music|Indian|Sufi',
  'Music|Indian|Tamil',
  'Music|Indian|Telugu',
  'Music|Inspirational',
  'Music|Instrumental',
  'Music|J-Pop',
  'Music|Jazz',
  'Music|Jazz|Avant-Garde Jazz',
  'Music|Jazz|Bebop',
  'Music|Jazz|Big Band',
  'Music|Jazz|Contemporary Jazz',
  'Music|Jazz|Cool',
  'Music|Jazz|Crossover Jazz',
  'Music|Jazz|Dixieland',
  'Music|Jazz|Fusion',
  'Music|Jazz|Hard Bop',
  'Music|Jazz|Latin Jazz',
  'Music|Jazz|Mainstream Jazz',
  'Music|Jazz|Ragtime',
  'Music|Jazz|Smooth Jazz',
  'Music|Jazz|Trad Jazz',
  'Music|Jazz|Vocal Jazz',
  'Music|Karaoke',
  'Music|Kayokyoku',
  'Music|Korean',
  'Music|Korean|Korean Traditional',
  'Music|Latin',
  'Music|Latin|Alternative & Rock in Spanish',
  'Music|Latin|Baladas y Boleros',
  'Music|Latin|Contemporary Latin',
  'Music|Latin|Latin Jazz',
  'Music|Latin|Latin Urban',
  'Music|Latin|Pop in Spanish',
  'Music|Latin|Raices',
  'Music|Latin|Regional Mexicano',
  'Music|Latin|Salsa y Tropical',
  'Music|Marching Bands',
  'Music|New Age',
  'Music|New Age|Healing',
  'Music|New Age|Meditation',
  'Music|New Age|Nature',
  'Music|New Age|Relaxation',
  'Music|New Age|Travel',
  'Music|New Age|Yoga',
  'Music|Pop',
  'Music|Pop|Adult Contemporary',
  'Music|Pop|Britpop',
  'Music|Pop|Cantopop',
  'Music|Pop|Indo Pop',
  'Music|Pop|K-Pop',
  'Music|Pop|Korean Folk-Pop',
  'Music|Pop|Malaysian Pop',
  'Music|Pop|Mandopop',
  'Music|Pop|Manilla Sound',
  'Music|Pop|Oldies',
  'Music|Pop|Original Pilipino Music',
  'Music|Pop|Pinoy Pop',
  'Music|Pop|Pop/Rock',
  'Music|Pop|Soft Rock',
  'Music|Pop|Tai-Pop',
  'Music|Pop|Teen Pop',
  'Music|Pop|Thai Pop',
  'Music|R&B/Soul',
  'Music|R&B/Soul|Contemporary R&B',
  'Music|R&B/Soul|Disco',
  'Music|R&B/Soul|Doo Wop',
  'Music|R&B/Soul|Funk',
  'Music|R&B/Soul|Motown',
  'Music|R&B/Soul|Neo-Soul',
  'Music|R&B/Soul|Soul',
  'Music|Reggae',
  'Music|Reggae|Dub',
  'Music|Reggae|Lovers Rock',
  'Music|Reggae|Modern Dancehall',
  'Music|Reggae|Roots Reggae',
  'Music|Reggae|Ska',
  'Music|Rock',
  'Music|Rock|Adult Alternative',
  'Music|Rock|American Trad Rock',
  'Music|Rock|Arena Rock',
  'Music|Rock|Blues-Rock',
  'Music|Rock|British Invasion',
  'Music|Rock|Chinese Rock',
  'Music|Rock|Death Metal/Black Metal',
  'Music|Rock|Glam Rock',
  'Music|Rock|Hair Metal',
  'Music|Rock|Hard Rock',
  'Music|Rock|Heavy Metal',
  'Music|Rock|Jam Bands',
  'Music|Rock|Korean Rock',
  'Music|Rock|Prog-Rock/Art Rock',
  'Music|Rock|Psychedelic',
  'Music|Rock|Rock & Roll',
  'Music|Rock|Rockabilly',
  'Music|Rock|Roots Rock',
  'Music|Rock|Singer/Songwriter',
  'Music|Rock|Southern Rock',
  'Music|Rock|Surf',
  'Music|Rock|Tex-Mex',
  'Music|Singer/Songwriter',
  'Music|Singer/Songwriter|Alternative Folk',
  'Music|Singer/Songwriter|Contemporary Folk',
  'Music|Singer/Songwriter|Contemporary Singer/Songwriter',
  'Music|Singer/Songwriter|Folk-Rock',
  'Music|Singer/Songwriter|New Acoustic',
  'Music|Singer/Songwriter|Traditional Folk',
  'Music|Soundtrack',
  'Music|Soundtrack|Foreign Cinema',
  'Music|Soundtrack|Musicals',
  'Music|Soundtrack|Original Score',
  'Music|Soundtrack|Sound Effects',
  'Music|Soundtrack|Soundtrack',
  'Music|Soundtrack|TV Soundtrack',
  'Music|Soundtrack|Video Game',
  'Music|Spoken Word',
  'Music|Vocal',
  'Music|Vocal|Standards',
  'Music|Vocal|Traditional Pop',
  'Music|Vocal|Trot',
  'Music|Vocal|Vocal Pop',
  'Music|World',
  'Music|World|Africa',
  'Music|World|Afrikaans',
  'Music|World|Afro-Beat',
  'Music|World|Afro-Pop',
  'Music|World|Arabesque',
  'Music|World|Asia',
  'Music|World|Australia',
  'Music|World|Cajun',
  'Music|World|Calypso',
  'Music|World|Caribbean',
  'Music|World|Celtic',
  'Music|World|Celtic Folk',
  'Music|World|Contemporary Celtic',
  'Music|World|Dangdut',
  'Music|World|Dini',
  'Music|World|Europe',
  'Music|World|Fado',
  'Music|World|Farsi',
  'Music|World|Flamenco',
  'Music|World|France',
  'Music|World|Halk',
  'Music|World|Hawaii',
  'Music|World|Iberia',
  'Music|World|Indonesian Religious',
  'Music|World|Israeli',
  'Music|World|Japan',
  'Music|World|Klezmer',
  'Music|World|North America',
  'Music|World|Polka',
  'Music|World|Russian',
  'Music|World|Russian Chanson',
  'Music|World|Sanat',
  'Music|World|Soca',
  'Music|World|South Africa',
  'Music|World|South America',
  'Music|World|Tango',
  'Music|World|Traditional Celtic',
  'Music|World|Turkish',
  'Music|World|Worldbeat',
  'Music|World|Zydeco'
]

const musicGenreNames = [
  'Music',
  'Alternative',
  'Chinese Alt',
  'College Rock',
  'EMO',
  'Goth Rock',
  'Grunge',
  'Indie Pop',
  'Indie Rock',
  'Korean Indie',
  'New Wave',
  'Pop Punk',
  'Punk',
  'Anime',
  'Arabic',
  'Arabic Pop',
  'Islamic',
  'Khaleeji',
  'North African',
  'Blues',
  'Acoustic Blues',
  'Chicago Blues',
  'Classic Blues',
  'Contemporary Blues',
  'Country Blues',
  'Delta Blues',
  'Electric Blues',
  'Brazilian',
  'Axé',
  'Baile Funk',
  'Bossa Nova',
  'Choro',
  'Forró',
  'Frevo',
  'MPB',
  'Pagode',
  'Samba',
  'Sertanejo',
  "Children's Music",
  'Lullabies',
  'Sing-Along',
  'Stories',
  'Chinese',
  'Chinese Classical',
  'Chinese Flute',
  'Chinese Opera',
  'Chinese Orchestral',
  'Chinese Regional Folk',
  'Chinese Strings',
  'Taiwanese Folk',
  'Tibetan Native Music',
  'Christian & Gospel',
  'CCM',
  'Christian Metal',
  'Christian Pop',
  'Christian Rap',
  'Christian Rock',
  'Classic Christian',
  'Contemporary Gospel',
  'Gospel',
  'Praise & Worship',
  'Southern Gospel',
  'Traditional Gospel',
  'Classical',
  'Art Song',
  'Avant-Garde',
  'Baroque Era',
  'Brass & Woodwinds',
  'Cantata',
  'Cello',
  'Chamber Music',
  'Chant',
  'Choral',
  'Classical Crossover',
  'Classical Era',
  'Contemporary Era',
  'Electronic',
  'Guitar',
  'Impressionist',
  'Medieval Era',
  'Minimalism',
  'Modern Era',
  'Opera',
  'Oratorio',
  'Orchestral',
  'Percussion',
  'Piano',
  'Renaissance',
  'Romantic Era',
  'Sacred',
  'Solo Instrumental',
  'Violin',
  'Comedy',
  'Novelty',
  'Standup Comedy',
  'Country',
  'Alternative Country',
  'Americana',
  'Bluegrass',
  'Contemporary Bluegrass',
  'Contemporary Country',
  'Country Gospel',
  'Honky Tonk',
  'Outlaw Country',
  'Thai Country',
  'Traditional Bluegrass',
  'Traditional Country',
  'Urban Cowboy',
  'Cuban',
  'Bolero',
  'Chachacha',
  'Guajira',
  'Guaracha',
  'Mambo',
  'Son',
  'Timba',
  'Dance',
  'Breakbeat',
  'Garage',
  'Hardcore',
  'House',
  "Jungle/Drum'n'bass",
  'Techno',
  'Trance',
  'Disney',
  'Easy Listening',
  'Lounge',
  'Swing',
  'Electronic',
  'Ambient',
  'Bass',
  'Downtempo',
  'Dubstep',
  'Electronica',
  'IDM/Experimental',
  'Industrial',
  'Enka',
  'Fitness & Workout',
  'Folk',
  'French Pop',
  'German Folk',
  'German Pop',
  'Hip Hop/Rap',
  'Alternative Rap',
  'Chinese Hip-Hop',
  'Dirty South',
  'East Coast Rap',
  'Gangsta Rap',
  'Hardcore Rap',
  'Hip-Hop',
  'Korean Hip-Hop',
  'Latin Rap',
  'Old School Rap',
  'Rap',
  'UK Hip Hop',
  'Underground Rap',
  'West Coast Rap',
  'Holiday',
  'Chanukah',
  'Christmas',
  "Christmas: Children's",
  'Christmas: Classic',
  'Christmas: Classical',
  'Christmas: Jazz',
  'Christmas: Modern',
  'Christmas: Pop',
  'Christmas: R&B',
  'Christmas: Religious',
  'Christmas: Rock',
  'Easter',
  'Halloween',
  'Thanksgiving',
  'Indian',
  'Bollywood',
  'Devotional & Spiritual',
  'Ghazals',
  'Indian Classical',
  'Indian Folk',
  'Indian Pop',
  'Punjabi Pop',
  'Rabindra Sangeet',
  'Regional Indian',
  'Sufi',
  'Tamil',
  'Telugu',
  'Inspirational',
  'Instrumental',
  'J-Pop',
  'Jazz',
  'Avant-Garde Jazz',
  'Bebop',
  'Big Band',
  'Contemporary Jazz',
  'Cool',
  'Crossover Jazz',
  'Dixieland',
  'Fusion',
  'Hard Bop',
  'Latin Jazz',
  'Mainstream Jazz',
  'Ragtime',
  'Smooth Jazz',
  'Trad Jazz',
  'Vocal Jazz',
  'Karaoke',
  'Kayokyoku',
  'Korean',
  'Korean Traditional',
  'Latin',
  'Alternative & Rock in Spanish',
  'Baladas y Boleros',
  'Contemporary Latin',
  'Latin Jazz',
  'Latin Urban',
  'Pop in Spanish',
  'Raices',
  'Regional Mexicano',
  'Salsa y Tropical',
  'Marching Bands',
  'New Age',
  'Healing',
  'Meditation',
  'Nature',
  'Relaxation',
  'Travel',
  'Yoga',
  'Pop',
  'Adult Contemporary',
  'Britpop',
  'Cantopop',
  'Indo Pop',
  'K-Pop',
  'Korean Folk-Pop',
  'Malaysian Pop',
  'Mandopop',
  'Manilla Sound',
  'Oldies',
  'Original Pilipino Music',
  'Pinoy Pop',
  'Pop/Rock',
  'Soft Rock',
  'Tai-Pop',
  'Teen Pop',
  'Thai Pop',
  'R&B/Soul',
  'Contemporary R&B',
  'Disco',
  'Doo Wop',
  'Funk',
  'Motown',
  'Neo-Soul',
  'Soul',
  'Reggae',
  'Dub',
  'Lovers Rock',
  'Modern Dancehall',
  'Roots Reggae',
  'Ska',
  'Rock',
  'Adult Alternative',
  'American Trad Rock',
  'Arena Rock',
  'Blues-Rock',
  'British Invasion',
  'Chinese Rock',
  'Death Metal/Black Metal',
  'Glam Rock',
  'Hair Metal',
  'Hard Rock',
  'Heavy Metal',
  'Jam Bands',
  'Korean Rock',
  'Prog-Rock/Art Rock',
  'Psychedelic',
  'Rock & Roll',
  'Rockabilly',
  'Roots Rock',
  'Singer/Songwriter',
  'Southern Rock',
  'Surf',
  'Tex-Mex',
  'Singer/Songwriter',
  'Alternative Folk',
  'Contemporary Folk',
  'Contemporary Singer/Songwriter',
  'Folk-Rock',
  'New Acoustic',
  'Traditional Folk',
  'Soundtrack',
  'Foreign Cinema',
  'Musicals',
  'Original Score',
  'Sound Effects',
  'Soundtrack',
  'TV Soundtrack',
  'Video Game',
  'Spoken Word',
  'Vocal',
  'Standards',
  'Traditional Pop',
  'Trot',
  'Vocal Pop',
  'World',
  'Africa',
  'Afrikaans',
  'Afro-Beat',
  'Afro-Pop',
  'Arabesque',
  'Asia',
  'Australia',
  'Cajun',
  'Calypso',
  'Caribbean',
  'Celtic',
  'Celtic Folk',
  'Contemporary Celtic',
  'Dangdut',
  'Dini',
  'Europe',
  'Fado',
  'Farsi',
  'Flamenco',
  'France',
  'Halk',
  'Hawaii',
  'Iberia',
  'Indonesian Religious',
  'Israeli',
  'Japan',
  'Klezmer',
  'North America',
  'Polka',
  'Russian',
  'Russian Chanson',
  'Sanat',
  'Soca',
  'South Africa',
  'South America',
  'Tango',
  'Traditional Celtic',
  'Turkish',
  'Worldbeat',
  'Zydeco'
]

const musicGenreCodes = [
  'MUSIC-00',
  'ALTERNATIVE-00',
  'CHINESE-ALT-00',
  'COLLEGE-ROCK-00',
  'EMO-00',
  'GOTH-ROCK-00',
  'GRUNGE-00',
  'INDIE-POP-00',
  'INDIE-ROCK-00',
  'KOREAN-INDIE-00',
  'NEW-WAVE-00',
  'POP-PUNK-00',
  'PUNK-00',
  'ANIME-00',
  'MIDDLE-EAST-00',
  'ARABIC-POP-00',
  'ISLAMIC-00',
  'KHALEEJI-00',
  'NORTH-AFRICAN-00',
  'BLUES-00',
  'ACOUSTIC-BLUES-00',
  'CHICAGO-BLUES-00',
  'CLASSIC-BLUES-00',
  'CONTEMPORARY-BLUES-00',
  'COUNTRY-BLUES-00',
  'DELTA-BLUES-00',
  'ELECTRIC-BLUES-00',
  'BRAZILIAN-00',
  'AXE-00',
  'BAILE-FUNK-00',
  'BOSSA-NOVA-00',
  'CHORO-00',
  'FORRO-00',
  'FREVO-00',
  'MPB-00',
  'PAGODE-00',
  'SAMBA-00',
  'SERTANEJO-00',
  'CHILDREN-MUSIC-00',
  'LULLABIES-00',
  'SING-ALONG-00',
  'STORIES-00',
  'CHINESE-00',
  'CHINESE-CLASSICAL-00',
  'CHINESE-FLUTE-00',
  'CHINESE-OPERA-00',
  'CHINESE-ORCHESTRAL-00',
  'CHINESE-REGIONAL-FOLK-00',
  'CHINESE-STRINGS-00',
  'TAIWANESE-FOLK-00',
  'TIBETAN-NATIVE-MUSIC-00',
  'CHRISTIAN-GOSPEL-00',
  'CCM-00',
  'CHRISTIAN-METAL-00',
  'CHRISTIAN-POP-00',
  'CHRISTIAN-RAP-00',
  'CHRISTIAN-ROCK-00',
  'CLASSIC-CHRISTIAN-00',
  'CONTEMPORARY-GOSPEL-00',
  'GOSPEL-00',
  'PRAISE-WORSHIP-00',
  'SOUTHERN-GOSPEL-00',
  'TRADITIONAL-GOSPEL-00',
  'CLASSICAL-00',
  'ART-SONG-00',
  'AVANT-GARDE-00',
  'BAROQUE-00',
  'BRASS-WOODWINDS-00',
  'CANTATA-00',
  'CELLO-00',
  'CHAMBER-MUSIC-00',
  'CHANT-00',
  'CHORAL-00',
  'CLASSICAL-CROSSOVER-00',
  'HIGH-CLASSICAL-00',
  'CONTEMPORARY-ERA-00',
  'ELECTRONIC-01',
  'GUITAR-00',
  'IMPRESSIONIST-00',
  'MEDIEVAL-00',
  'MINIMALISM-00',
  'MODERN-COMPOSITION-00',
  'OPERA-00',
  'ORATORIO-00',
  'ORCHESTRAL-00',
  'PERCUSSION-00',
  'PIANO-00',
  'RENAISSANCE-00',
  'ROMANTIC-00',
  'SACRED-00',
  'SOLO-INSTRUMENTAL-00',
  'VIOLIN-00',
  'COMEDY-00',
  'NOVELTY-00',
  'STANDUP-COMEDY-00',
  'COUNTRY-00',
  'ALTERNATIVE-COUNTRY-00',
  'AMERICANA-00',
  'BLUEGRASS-00',
  'CONTEMPORARY-BLUEGRASS-00',
  'CONTEMPORARY-COUNTRY-00',
  'COUNTRY-GOSPEL-00',
  'HONKY-TONK-00',
  'OUTLAW-COUNTRY-00',
  'THAI-COUNTRY-00',
  'TRADITIONAL-BLUEGRASS-00',
  'TRADITIONAL-COUNTRY-00',
  'URBAN-COWBOY-00',
  'CUBAN-00',
  'BOLERO-00',
  'CHACHACHA-00',
  'GUAJIRA-00',
  'GUARACHA-00',
  'MAMBO-00',
  'SON-00',
  'TIMBA-00',
  'DANCE-00',
  'BREAKBEAT-00',
  'GARAGE-00',
  'HARDCORE-00',
  'HOUSE-00',
  'JUNGLE-DRUM-N-BASS-00',
  'TECHNO-00',
  'TRANCE-00',
  'DISNEY-00',
  'EASY-LISTENING-00',
  'LOUNGE-00',
  'SWING-00',
  'ELECTRONIC-00',
  'AMBIENT-00',
  'BASS-00',
  'DOWNTEMPO-00',
  'DUBSTEP-00',
  'ELECTRONICA-00',
  'IDM-EXPERIMENTAL-00',
  'INDUSTRIAL-00',
  'ENKA-00',
  'FITNESS-WORKOUT-00',
  'FOLK-00',
  'FRENCH-POP-00',
  'GERMAN-FOLK-00',
  'GERMAN-POP-00',
  'HIP-HOP-RAP-00',
  'ALTERNATIVE-RAP-00',
  'CHINESE-HIP-HOP-00',
  'DIRTY-SOUTH-00',
  'EAST-COAST-RAP-00',
  'GANGSTA-RAP-00',
  'HARDCORE-RAP-00',
  'HIP-HOP-00',
  'KOREAN-HIP-HOP-00',
  'LATIN-RAP-00',
  'OLD-SCHOOL-RAP-00',
  'RAP-00',
  'UK-HIP-HOP-00',
  'UNDERGROUND-RAP-00',
  'WEST-COAST-RAP-00',
  'HOLIDAY-00',
  'CHANUKAH-00',
  'CHRISTMAS-00',
  'CHRISTMAS-CHILDRENS-00',
  'CHRISTMAS-CLASSIC-00',
  'CHRISTMAS-CLASSICAL-00',
  'CHRISTMAS-JAZZ-00',
  'CHRISTMAS-MODERN-00',
  'CHRISTMAS-POP-00',
  'CHRISTMAS-R-B-00',
  'CHRISTMAS-RELIGIOUS-00',
  'CHRISTMAS-ROCK-00',
  'EASTER-00',
  'HALLOWEEN-00',
  'THANKSGIVING-00',
  'INDIAN-00',
  'BOLLYWOOD-00',
  'DEVOTIONAL-SPIRITUAL-00',
  'GHAZALS-00',
  'INDIAN-CLASSICAL-00',
  'INDIAN-FOLK-00',
  'INDIAN-POP-00',
  'PUNJABI-POP-00',
  'RABINDRA-SANGEET-00',
  'REGIONAL-INDIAN-00',
  'SUFI-AND-GHAZALS-00',
  'TAMIL-00',
  'TELUGU-00',
  'INSPIRATIONAL-00',
  'INSTRUMENTAL-00',
  'J-POP-00',
  'JAZZ-00',
  'AVANT-GARDE-JAZZ-00',
  'BOP-00',
  'BIG-BAND-00',
  'CONTEMPORARY-JAZZ-00',
  'COOL-00',
  'CROSSOVER-JAZZ-00',
  'DIXIELAND-00',
  'FUSION-00',
  'HARD-BOP-00',
  'LATIN-JAZZ-00',
  'MAINSTREAM-JAZZ-00',
  'RAGTIME-00',
  'SMOOTH-JAZZ-00',
  'TRAD-JAZZ-00',
  'VOCAL-JAZZ-00',
  'KARAOKE-00',
  'KAYOKYOKU-00',
  'KOREAN-00',
  'KOREAN-CLASSICAL-00',
  'LATIN-00',
  'ALTERNATIVO-ROCK-LATINO-00',
  'BALADAS-Y-BOLEROS-00',
  'CONTEMPORARY-LATIN-00',
  'LATIN-JAZZ-01',
  'REGGAETON-Y-HIP-HOP-00',
  'POP-LATINO-00',
  'RAICES-00',
  'REGIONAL-MEXICANO-00',
  'SALSA-Y-TROPICAL-00',
  'MARCHING-BANDS-00',
  'NEW-AGE-00',
  'HEALING-00',
  'MEDITATION-00',
  'NATURE-00',
  'RELAXATION-00',
  'TRAVEL-00',
  'YOGA-00',
  'POP-00',
  'ADULT-CONTEMPORARY-00',
  'BRITPOP-00',
  'CANTOPOP-HK-POP-00',
  'INDO-POP-00',
  'K-POP-00',
  'KOREAN-FOLK-POP-00',
  'MALAYSIAN-POP-00',
  'MANDOPOP-00',
  'MANILLA-SOUND-00',
  'OLDIES-00',
  'ORIGINAL-PILIPINO-MUSIC-00',
  'PINOY-POP-00',
  'POP-ROCK-00',
  'SOFT-ROCK-00',
  'TAI-POP-00',
  'TEEN-POP-00',
  'THAI-POP-00',
  'R-B-SOUL-00',
  'CONTEMPORARY-R-B-00',
  'DISCO-00',
  'DOO-WOP-00',
  'FUNK-00',
  'MOTOWN-00',
  'NEO-SOUL-00',
  'SOUL-00',
  'REGGAE-00',
  'DUB-00',
  'LOVERS-ROCK-00',
  'DANCEHALL-00',
  'ROOTS-REGGAE-00',
  'SKA-00',
  'ROCK-00',
  'ADULT-ALTERNATIVE-00',
  'AMERICAN-TRAD-ROCK-00',
  'ARENA-ROCK-00',
  'BLUES-ROCK-00',
  'BRITISH-INVASION-00',
  'CHINESE-ROCK-00',
  'DEATH-METAL-BLACK-METAL-00',
  'GLAM-ROCK-00',
  'HAIR-METAL-00',
  'HARD-ROCK-00',
  'HEAVY-METAL-00',
  'JAM-BANDS-00',
  'KOREAN-ROCK-00',
  'PROG-ROCK-ART-ROCK-00',
  'PSYCHEDELIC-00',
  'ROCK-ROLL-00',
  'ROCKABILLY-00',
  'ROOTS-ROCK-00',
  'SINGER-SONGWRITER-01',
  'SOUTHERN-ROCK-00',
  'SURF-00',
  'TEX-MEX-00',
  'SINGER-SONGWRITER-00',
  'ALTERNATIVE-FOLK-00',
  'CONTEMPORARY-FOLK-00',
  'CONTEMPORARY-SINGER-SONGWRITER-00',
  'FOLK-ROCK-00',
  'NEW-ACOUSTIC-00',
  'TRADITIONAL-FOLK-00',
  'SOUNDTRACK-00',
  'FOREIGN-CINEMA-00',
  'MUSICALS-00',
  'ORIGINAL-SCORE-00',
  'SOUND-EFFECT-00',
  'FILM-SOUNDTRACK-00',
  'TV-SOUNDTRACK-00',
  'VIDEOGAME-00',
  'SPOKEN-WORD-00',
  'VOCAL-00',
  'STANDARDS-00',
  'TRADITIONAL-POP-00',
  'TROT-00',
  'VOCAL-POP-00',
  'WORLD-00',
  'AFRICA-00',
  'AFRIKAANS-00',
  'AFRO-BEAT-00',
  'AFRO-POP-00',
  'ARABESQUE-00',
  'ASIA-00',
  'AUSTRALIA-00',
  'CAJUN-00',
  'CALYPSO-00',
  'CARIBBEAN-00',
  'CELTIC-00',
  'CELTIC-FOLK-00',
  'CONTEMPORARY-CELTIC-00',
  'DANGDUT-00',
  'DINI-00',
  'EUROPE-00',
  'FADO-00',
  'FARSI-00',
  'FLAMENCO-00',
  'FRANCE-00',
  'HALK-00',
  'HAWAII-00',
  'IBERIA-00',
  'INDONESIAN-RELIGIOUS-00',
  'ISRAELI-00',
  'JAPAN-00',
  'KLEZMER-00',
  'NORTH-AMERICA-00',
  'POLKA-00',
  'RUSSIAN-00',
  'RUSSIAN-CHANSON-00',
  'SANAT-00',
  'SOCA-00',
  'SOUTH-AFRICA-00',
  'SOUTH-AMERICA-00',
  'TANGO-00',
  'TRADITIONAL-CELTIC-00',
  'TURKISH-00',
  'WORLDBEAT-00',
  'ZYDECO-00'
]

const musicVideoGenrePaths = [
  'Music Videos',
  'Music Videos|Alternative',
  'Music Videos|Alternative|Chinese Alt',
  'Music Videos|Alternative|College Rock',
  'Music Videos|Alternative|EMO',
  'Music Videos|Alternative|Goth Rock',
  'Music Videos|Alternative|Grunge',
  'Music Videos|Alternative|Indie Pop',
  'Music Videos|Alternative|Indie Rock',
  'Music Videos|Alternative|Korean Indie',
  'Music Videos|Alternative|New Wave',
  'Music Videos|Alternative|Pop Punk',
  'Music Videos|Alternative|Punk',
  'Music Videos|Anime',
  'Music Videos|Arabic',
  'Music Videos|Arabic|Arabic Pop',
  'Music Videos|Arabic|Islamic',
  'Music Videos|Arabic|Khaleeji',
  'Music Videos|Arabic|North African',
  'Music Videos|Blues',
  'Music Videos|Blues|Acoustic Blues',
  'Music Videos|Blues|Chicago Blues',
  'Music Videos|Blues|Classic Blues',
  'Music Videos|Blues|Contemporary Blues',
  'Music Videos|Blues|Country Blues',
  'Music Videos|Blues|Delta Blues',
  'Music Videos|Blues|Electric Blues',
  'Music Videos|Brazilian',
  'Music Videos|Brazilian|Axé',
  'Music Videos|Brazilian|Baile Funk',
  'Music Videos|Brazilian|Bossa Nova',
  'Music Videos|Brazilian|Choro',
  'Music Videos|Brazilian|Forró',
  'Music Videos|Brazilian|Frevo',
  'Music Videos|Brazilian|MPB',
  'Music Videos|Brazilian|Pagode',
  'Music Videos|Brazilian|Samba',
  'Music Videos|Brazilian|Sertanejo',
  "Music Videos|Children's Music",
  "Music Videos|Children's Music|Lullabies",
  "Music Videos|Children's Music|Sing-Along",
  "Music Videos|Children's Music|Stories",
  'Music Videos|Chinese',
  'Music Videos|Chinese|Chinese Classical',
  'Music Videos|Chinese|Chinese Flute',
  'Music Videos|Chinese|Chinese Opera',
  'Music Videos|Chinese|Chinese Orchestral',
  'Music Videos|Chinese|Chinese Regional Folk',
  'Music Videos|Chinese|Chinese Strings',
  'Music Videos|Chinese|Taiwanese Folk',
  'Music Videos|Chinese|Tibetan Native Music',
  'Music Videos|Christian & Gospel',
  'Music Videos|Christian & Gospel|CCM',
  'Music Videos|Christian & Gospel|Christian Metal',
  'Music Videos|Christian & Gospel|Christian Pop',
  'Music Videos|Christian & Gospel|Christian Rap',
  'Music Videos|Christian & Gospel|Christian Rock',
  'Music Videos|Christian & Gospel|Classic Christian',
  'Music Videos|Christian & Gospel|Contemporary Gospel',
  'Music Videos|Christian & Gospel|Gospel',
  'Music Videos|Christian & Gospel|Praise & Worship',
  'Music Videos|Christian & Gospel|Southern Gospel',
  'Music Videos|Christian & Gospel|Traditional Gospel',
  'Music Videos|Classical',
  'Music Videos|Classical|Art Song',
  'Music Videos|Classical|Avant-Garde',
  'Music Videos|Classical|Baroque Era',
  'Music Videos|Classical|Brass & Woodwinds',
  'Music Videos|Classical|Cantata',
  'Music Videos|Classical|Cello',
  'Music Videos|Classical|Chamber Music',
  'Music Videos|Classical|Chant',
  'Music Videos|Classical|Choral',
  'Music Videos|Classical|Classical Crossover',
  'Music Videos|Classical|Classical Era',
  'Music Videos|Classical|Contemporary Era',
  'Music Videos|Classical|Electronic',
  'Music Videos|Classical|Guitar',
  'Music Videos|Classical|Impressionist',
  'Music Videos|Classical|Medieval Era',
  'Music Videos|Classical|Minimalism',
  'Music Videos|Classical|Modern Era',
  'Music Videos|Classical|Opera',
  'Music Videos|Classical|Oratorio',
  'Music Videos|Classical|Orchestral',
  'Music Videos|Classical|Percussion',
  'Music Videos|Classical|Piano',
  'Music Videos|Classical|Renaissance',
  'Music Videos|Classical|Romantic Era',
  'Music Videos|Classical|Sacred',
  'Music Videos|Classical|Solo Instrumental',
  'Music Videos|Classical|Violin',
  'Music Videos|Comedy',
  'Music Videos|Comedy|Novelty',
  'Music Videos|Comedy|Standup Comedy',
  'Music Videos|Country',
  'Music Videos|Country|Alternative Country',
  'Music Videos|Country|Americana',
  'Music Videos|Country|Bluegrass',
  'Music Videos|Country|Contemporary Bluegrass',
  'Music Videos|Country|Contemporary Country',
  'Music Videos|Country|Country Gospel',
  'Music Videos|Country|Honky Tonk',
  'Music Videos|Country|Outlaw Country',
  'Music Videos|Country|Thai Country',
  'Music Videos|Country|Traditional Bluegrass',
  'Music Videos|Country|Traditional Country',
  'Music Videos|Country|Urban Cowboy',
  'Music Videos|Dance',
  'Music Videos|Dance|Breakbeat',
  'Music Videos|Dance|Garage',
  'Music Videos|Dance|Hardcore',
  'Music Videos|Dance|House',
  "Music Videos|Dance|Jungle/Drum'n'bass",
  'Music Videos|Dance|Techno',
  'Music Videos|Dance|Trance',
  'Music Videos|Disney',
  'Music Videos|Easy Listening',
  'Music Videos|Easy Listening|Lounge',
  'Music Videos|Easy Listening|Swing',
  'Music Videos|Electronic',
  'Music Videos|Electronic|Ambient',
  'Music Videos|Electronic|Bass',
  'Music Videos|Electronic|Downtempo',
  'Music Videos|Electronic|Dubstep',
  'Music Videos|Electronic|Electronica',
  'Music Videos|Electronic|IDM/Experimental',
  'Music Videos|Electronic|Industrial',
  'Music Videos|Enka',
  'Music Videos|Fitness & Workout',
  'Music Videos|Folk',
  'Music Videos|French Pop',
  'Music Videos|German Folk',
  'Music Videos|German Pop',
  'Music Videos|Hip Hop/Rap',
  'Music Videos|Hip Hop/Rap|Alternative Rap',
  'Music Videos|Hip Hop/Rap|Chinese Hip-Hop',
  'Music Videos|Hip Hop/Rap|Dirty South',
  'Music Videos|Hip Hop/Rap|East Coast Rap',
  'Music Videos|Hip Hop/Rap|Gangsta Rap',
  'Music Videos|Hip Hop/Rap|Hardcore Rap',
  'Music Videos|Hip Hop/Rap|Hip-Hop',
  'Music Videos|Hip Hop/Rap|Korean Hip-Hop',
  'Music Videos|Hip Hop/Rap|Latin Rap',
  'Music Videos|Hip Hop/Rap|Old School Rap',
  'Music Videos|Hip Hop/Rap|Rap',
  'Music Videos|Hip Hop/Rap|UK Hip Hop',
  'Music Videos|Hip Hop/Rap|Underground Rap',
  'Music Videos|Hip Hop/Rap|West Coast Rap',
  'Music Videos|Holiday',
  'Music Videos|Holiday|Chanukah',
  'Music Videos|Holiday|Christmas',
  "Music Videos|Holiday|Christmas: Children's",
  'Music Videos|Holiday|Christmas: Classic',
  'Music Videos|Holiday|Christmas: Classical',
  'Music Videos|Holiday|Christmas: Jazz',
  'Music Videos|Holiday|Christmas: Modern',
  'Music Videos|Holiday|Christmas: Pop',
  'Music Videos|Holiday|Christmas: R&B',
  'Music Videos|Holiday|Christmas: Religious',
  'Music Videos|Holiday|Christmas: Rock',
  'Music Videos|Holiday|Easter',
  'Music Videos|Holiday|Halloween',
  'Music Videos|Holiday|Thanksgiving',
  'Music Videos|Indian',
  'Music Videos|Indian|Bollywood',
  'Music Videos|Indian|Devotional & Spiritual',
  'Music Videos|Indian|Ghazals',
  'Music Videos|Indian|Indian Classical',
  'Music Videos|Indian|Indian Folk',
  'Music Videos|Indian|Indian Pop',
  'Music Videos|Indian|Regional Indian',
  'Music Videos|Indian|Sufi',
  'Music Videos|Indian|Tamil',
  'Music Videos|Indian|Telugu',
  'Music Videos|Inspirational',
  'Music Videos|Instrumental',
  'Music Videos|J-Pop',
  'Music Videos|Jazz',
  'Music Videos|Jazz|Avant-Garde Jazz',
  'Music Videos|Jazz|Bebop',
  'Music Videos|Jazz|Big Band',
  'Music Videos|Jazz|Contemporary Jazz',
  'Music Videos|Jazz|Cool',
  'Music Videos|Jazz|Crossover Jazz',
  'Music Videos|Jazz|Dixieland',
  'Music Videos|Jazz|Fusion',
  'Music Videos|Jazz|Hard Bop',
  'Music Videos|Jazz|Latin Jazz',
  'Music Videos|Jazz|Mainstream Jazz',
  'Music Videos|Jazz|Ragtime',
  'Music Videos|Jazz|Smooth Jazz',
  'Music Videos|Jazz|Trad Jazz',
  'Music Videos|Jazz|Vocal Jazz',
  'Music Videos|Karaoke',
  'Music Videos|Kayokyoku',
  'Music Videos|Korean',
  'Music Videos|Korean|Korean Traditional',
  'Music Videos|Latin',
  'Music Videos|Latin|Alternative & Rock in Spanish',
  'Music Videos|Latin|Baladas y Boleros',
  'Music Videos|Latin|Contemporary Latin',
  'Music Videos|Latin|Latin Jazz',
  'Music Videos|Latin|Latin Urban',
  'Music Videos|Latin|Pop in Spanish',
  'Music Videos|Latin|Raices',
  'Music Videos|Latin|Regional Mexicano',
  'Music Videos|Latin|Salsa y Tropical',
  'Music Videos|Marching Bands',
  'Music Videos|New Age',
  'Music Videos|New Age|Healing',
  'Music Videos|New Age|Meditation',
  'Music Videos|New Age|Nature',
  'Music Videos|New Age|Relaxation',
  'Music Videos|New Age|Travel',
  'Music Videos|New Age|Yoga',
  'Music Videos|Pop',
  'Music Videos|Pop|Adult Contemporary',
  'Music Videos|Pop|Britpop',
  'Music Videos|Pop|Cantopop',
  'Music Videos|Pop|Indo Pop',
  'Music Videos|Pop|K-Pop',
  'Music Videos|Pop|Korean Folk-Pop',
  'Music Videos|Pop|Malaysian Pop',
  'Music Videos|Pop|Mandopop',
  'Music Videos|Pop|Manilla Sound',
  'Music Videos|Pop|Oldies',
  'Music Videos|Pop|Original Pilipino Music',
  'Music Videos|Pop|Pinoy Pop',
  'Music Videos|Pop|Pop/Rock',
  'Music Videos|Pop|Soft Rock',
  'Music Videos|Pop|Tai-Pop',
  'Music Videos|Pop|Teen Pop',
  'Music Videos|Pop|Thai Pop',
  'Music Videos|R&B/Soul',
  'Music Videos|R&B/Soul|Contemporary R&B',
  'Music Videos|R&B/Soul|Disco',
  'Music Videos|R&B/Soul|Doo Wop',
  'Music Videos|R&B/Soul|Funk',
  'Music Videos|R&B/Soul|Motown',
  'Music Videos|R&B/Soul|Neo-Soul',
  'Music Videos|R&B/Soul|Soul',
  'Music Videos|Reggae',
  'Music Videos|Reggae|Dub',
  'Music Videos|Reggae|Lovers Rock',
  'Music Videos|Reggae|Modern Dancehall',
  'Music Videos|Reggae|Roots Reggae',
  'Music Videos|Reggae|Ska',
  'Music Videos|Rock',
  'Music Videos|Rock|Adult Alternative',
  'Music Videos|Rock|American Trad Rock',
  'Music Videos|Rock|Arena Rock',
  'Music Videos|Rock|Blues-Rock',
  'Music Videos|Rock|British Invasion',
  'Music Videos|Rock|Chinese Rock',
  'Music Videos|Rock|Death Metal/Black Metal',
  'Music Videos|Rock|Glam Rock',
  'Music Videos|Rock|Hair Metal',
  'Music Videos|Rock|Hard Rock',
  'Music Videos|Rock|Heavy Metal',
  'Music Videos|Rock|Jam Bands',
  'Music Videos|Rock|Korean Rock',
  'Music Videos|Rock|Prog-Rock/Art Rock',
  'Music Videos|Rock|Psychedelic',
  'Music Videos|Rock|Rock & Roll',
  'Music Videos|Rock|Rockabilly',
  'Music Videos|Rock|Roots Rock',
  'Music Videos|Rock|Singer/Songwriter',
  'Music Videos|Rock|Southern Rock',
  'Music Videos|Rock|Surf',
  'Music Videos|Rock|Tex-Mex',
  'Music Videos|Singer/Songwriter',
  'Music Videos|Singer/Songwriter|Alternative Folk',
  'Music Videos|Singer/Songwriter|Contemporary Folk',
  'Music Videos|Singer/Songwriter|Contemporary Singer/Songwriter',
  'Music Videos|Singer/Songwriter|Folk-Rock',
  'Music Videos|Singer/Songwriter|New Acoustic',
  'Music Videos|Singer/Songwriter|Traditional Folk',
  'Music Videos|Soundtrack',
  'Music Videos|Soundtrack|Foreign Cinema',
  'Music Videos|Soundtrack|Musicals',
  'Music Videos|Soundtrack|Original Score',
  'Music Videos|Soundtrack|Sound Effects',
  'Music Videos|Soundtrack|Soundtrack',
  'Music Videos|Soundtrack|TV Soundtrack',
  'Music Videos|Spoken Word',
  'Music Videos|Vocal',
  'Music Videos|Vocal|Standards',
  'Music Videos|Vocal|Traditional Pop',
  'Music Videos|Vocal|Trot',
  'Music Videos|Vocal|Vocal Pop',
  'Music Videos|World',
  'Music Videos|World|Africa',
  'Music Videos|World|Afrikaans',
  'Music Videos|World|Afro-Beat',
  'Music Videos|World|Afro-Pop',
  'Music Videos|World|Arabesque',
  'Music Videos|World|Asia',
  'Music Videos|World|Australia',
  'Music Videos|World|Cajun',
  'Music Videos|World|Calypso',
  'Music Videos|World|Caribbean',
  'Music Videos|World|Celtic',
  'Music Videos|World|Celtic Folk',
  'Music Videos|World|Contemporary Celtic',
  'Music Videos|World|Dangdut',
  'Music Videos|World|Dini',
  'Music Videos|World|Europe',
  'Music Videos|World|Fado',
  'Music Videos|World|Farsi',
  'Music Videos|World|Flamenco',
  'Music Videos|World|France',
  'Music Videos|World|Halk',
  'Music Videos|World|Hawaii',
  'Music Videos|World|Iberia',
  'Music Videos|World|Indonesian Religious',
  'Music Videos|World|Israeli',
  'Music Videos|World|Japan',
  'Music Videos|World|Klezmer',
  'Music Videos|World|North America',
  'Music Videos|World|Polka',
  'Music Videos|World|Russian',
  'Music Videos|World|Russian Chanson',
  'Music Videos|World|Sanat',
  'Music Videos|World|Soca',
  'Music Videos|World|South Africa',
  'Music Videos|World|South America',
  'Music Videos|World|Tango',
  'Music Videos|World|Traditional Celtic',
  'Music Videos|World|Turkish',
  'Music Videos|World|Worldbeat',
  'Music Videos|World|Zydeco'
]

const musicVideoGenreNames = [
  'Music Videos',
  'Alternative',
  'Chinese Alt',
  'College Rock',
  'EMO',
  'Goth Rock',
  'Grunge',
  'Indie Pop',
  'Indie Rock',
  'Korean Indie',
  'New Wave',
  'Pop Punk',
  'Punk',
  'Anime',
  'Arabic',
  'Arabic Pop',
  'Islamic',
  'Khaleeji',
  'North African',
  'Blues',
  'Acoustic Blues',
  'Chicago Blues',
  'Classic Blues',
  'Contemporary Blues',
  'Country Blues',
  'Delta Blues',
  'Electric Blues',
  'Brazilian',
  'Axé',
  'Baile Funk',
  'Bossa Nova',
  'Choro',
  'Forró',
  'Frevo',
  'MPB',
  'Pagode',
  'Samba',
  'Sertanejo',
  "Children's Music",
  'Lullabies',
  'Sing-Along',
  'Stories',
  'Chinese',
  'Chinese Classical',
  'Chinese Flute',
  'Chinese Opera',
  'Chinese Orchestral',
  'Chinese Regional Folk',
  'Chinese Strings',
  'Taiwanese Folk',
  'Tibetan Native Music',
  'Christian & Gospel',
  'CCM',
  'Christian Metal',
  'Christian Pop',
  'Christian Rap',
  'Christian Rock',
  'Classic Christian',
  'Contemporary Gospel',
  'Gospel',
  'Praise & Worship',
  'Southern Gospel',
  'Traditional Gospel',
  'Classical',
  'Art Song',
  'Avant-Garde',
  'Baroque Era',
  'Brass & Woodwinds',
  'Cantata',
  'Cello',
  'Chamber Music',
  'Chant',
  'Choral',
  'Classical Crossover',
  'Classical Era',
  'Contemporary Era',
  'Electronic',
  'Guitar',
  'Impressionist',
  'Medieval Era',
  'Minimalism',
  'Modern Era',
  'Opera',
  'Oratorio',
  'Orchestral',
  'Percussion',
  'Piano',
  'Renaissance',
  'Romantic Era',
  'Sacred',
  'Solo Instrumental',
  'Violin',
  'Comedy',
  'Novelty',
  'Standup Comedy',
  'Country',
  'Alternative Country',
  'Americana',
  'Bluegrass',
  'Contemporary Bluegrass',
  'Contemporary Country',
  'Country Gospel',
  'Honky Tonk',
  'Outlaw Country',
  'Thai Country',
  'Traditional Bluegrass',
  'Traditional Country',
  'Urban Cowboy',
  'Dance',
  'Breakbeat',
  'Garage',
  'Hardcore',
  'House',
  "Jungle/Drum'n'bass",
  'Techno',
  'Trance',
  'Disney',
  'Easy Listening',
  'Lounge',
  'Swing',
  'Electronic',
  'Ambient',
  'Bass',
  'Downtempo',
  'Dubstep',
  'Electronica',
  'IDM/Experimental',
  'Industrial',
  'Enka',
  'Fitness & Workout',
  'Folk',
  'French Pop',
  'German Folk',
  'German Pop',
  'Hip Hop/Rap',
  'Alternative Rap',
  'Chinese Hip-Hop',
  'Dirty South',
  'East Coast Rap',
  'Gangsta Rap',
  'Hardcore Rap',
  'Hip-Hop',
  'Korean Hip-Hop',
  'Latin Rap',
  'Old School Rap',
  'Rap',
  'UK Hip Hop',
  'Underground Rap',
  'West Coast Rap',
  'Holiday',
  'Chanukah',
  'Christmas',
  "Christmas: Children's",
  'Christmas: Classic',
  'Christmas: Classical',
  'Christmas: Jazz',
  'Christmas: Modern',
  'Christmas: Pop',
  'Christmas: R&B',
  'Christmas: Religious',
  'Christmas: Rock',
  'Easter',
  'Halloween',
  'Thanksgiving',
  'Indian',
  'Bollywood',
  'Devotional & Spiritual',
  'Ghazals',
  'Indian Classical',
  'Indian Folk',
  'Indian Pop',
  'Regional Indian',
  'Sufi',
  'Tamil',
  'Telugu',
  'Inspirational',
  'Instrumental',
  'J-Pop',
  'Jazz',
  'Avant-Garde Jazz',
  'Bebop',
  'Big Band',
  'Contemporary Jazz',
  'Cool',
  'Crossover Jazz',
  'Dixieland',
  'Fusion',
  'Hard Bop',
  'Latin Jazz',
  'Mainstream Jazz',
  'Ragtime',
  'Smooth Jazz',
  'Trad Jazz',
  'Vocal Jazz',
  'Karaoke',
  'Kayokyoku',
  'Korean',
  'Korean Traditional',
  'Latin',
  'Alternative & Rock in Spanish',
  'Baladas y Boleros',
  'Contemporary Latin',
  'Latin Jazz',
  'Latin Urban',
  'Pop in Spanish',
  'Raices',
  'Regional Mexicano',
  'Salsa y Tropical',
  'Marching Bands',
  'New Age',
  'Healing',
  'Meditation',
  'Nature',
  'Relaxation',
  'Travel',
  'Yoga',
  'Pop',
  'Adult Contemporary',
  'Britpop',
  'Cantopop',
  'Indo Pop',
  'K-Pop',
  'Korean Folk-Pop',
  'Malaysian Pop',
  'Mandopop',
  'Manilla Sound',
  'Oldies',
  'Original Pilipino Music',
  'Pinoy Pop',
  'Pop/Rock',
  'Soft Rock',
  'Tai-Pop',
  'Teen Pop',
  'Thai Pop',
  'R&B/Soul',
  'Contemporary R&B',
  'Disco',
  'Doo Wop',
  'Funk',
  'Motown',
  'Neo-Soul',
  'Soul',
  'Reggae',
  'Dub',
  'Lovers Rock',
  'Modern Dancehall',
  'Roots Reggae',
  'Ska',
  'Rock',
  'Adult Alternative',
  'American Trad Rock',
  'Arena Rock',
  'Blues-Rock',
  'British Invasion',
  'Chinese Rock',
  'Death Metal/Black Metal',
  'Glam Rock',
  'Hair Metal',
  'Hard Rock',
  'Heavy Metal',
  'Jam Bands',
  'Korean Rock',
  'Prog-Rock/Art Rock',
  'Psychedelic',
  'Rock & Roll',
  'Rockabilly',
  'Roots Rock',
  'Singer/Songwriter',
  'Southern Rock',
  'Surf',
  'Tex-Mex',
  'Singer/Songwriter',
  'Alternative Folk',
  'Contemporary Folk',
  'Contemporary Singer/Songwriter',
  'Folk-Rock',
  'New Acoustic',
  'Traditional Folk',
  'Soundtrack',
  'Foreign Cinema',
  'Musicals',
  'Original Score',
  'Sound Effects',
  'Soundtrack',
  'TV Soundtrack',
  'Spoken Word',
  'Vocal',
  'Standards',
  'Traditional Pop',
  'Trot',
  'Vocal Pop',
  'World',
  'Africa',
  'Afrikaans',
  'Afro-Beat',
  'Afro-Pop',
  'Arabesque',
  'Asia',
  'Australia',
  'Cajun',
  'Calypso',
  'Caribbean',
  'Celtic',
  'Celtic Folk',
  'Contemporary Celtic',
  'Dangdut',
  'Dini',
  'Europe',
  'Fado',
  'Farsi',
  'Flamenco',
  'France',
  'Halk',
  'Hawaii',
  'Iberia',
  'Indonesian Religious',
  'Israeli',
  'Japan',
  'Klezmer',
  'North America',
  'Polka',
  'Russian',
  'Russian Chanson',
  'Sanat',
  'Soca',
  'South Africa',
  'South America',
  'Tango',
  'Traditional Celtic',
  'Turkish',
  'Worldbeat',
  'Zydeco'
]

const musicVideoGenreCodes = [
  'MUSIC-VIDEOS-00',
  'ALTERNATIVE-00',
  'CHINESE-ALT-00',
  'COLLEGE-ROCK-00',
  'EMO-00',
  'GOTH-ROCK-00',
  'GRUNGE-00',
  'INDIE-POP-00',
  'INDIE-ROCK-00',
  'KOREAN-INDIE-00',
  'NEW-WAVE-00',
  'POP-PUNK-00',
  'PUNK-00',
  'ANIME-00',
  'MIDDLE-EAST-00',
  'ARABIC-POP-00',
  'ISLAMIC-00',
  'KHALEEJI-00',
  'NORTH-AFRICAN-00',
  'BLUES-00',
  'ACOUSTIC-BLUES-00',
  'CHICAGO-BLUES-00',
  'CLASSIC-BLUES-00',
  'CONTEMPORARY-BLUES-00',
  'COUNTRY-BLUES-00',
  'DELTA-BLUES-00',
  'ELECTRIC-BLUES-00',
  'BRAZILIAN-00',
  'AXE-00',
  'BAILE-FUNK-00',
  'BOSSA-NOVA-00',
  'CHORO-00',
  'FORRO-00',
  'FREVO-00',
  'MPB-00',
  'PAGODE-00',
  'SAMBA-00',
  'SERTANEJO-00',
  'CHILDREN-MUSIC-00',
  'LULLABIES-00',
  'SING-ALONG-00',
  'STORIES-00',
  'CHINESE-00',
  'CHINESE-CLASSICAL-00',
  'CHINESE-FLUTE-00',
  'CHINESE-OPERA-00',
  'CHINESE-ORCHESTRAL-00',
  'CHINESE-REGIONAL-FOLK-00',
  'CHINESE-STRINGS-00',
  'TAIWANESE-FOLK-00',
  'TIBETAN-NATIVE-MUSIC-00',
  'CHRISTIAN-GOSPEL-00',
  'CCM-00',
  'CHRISTIAN-METAL-00',
  'CHRISTIAN-POP-00',
  'CHRISTIAN-RAP-00',
  'CHRISTIAN-ROCK-00',
  'CLASSIC-CHRISTIAN-00',
  'CONTEMPORARY-GOSPEL-00',
  'GOSPEL-00',
  'PRAISE-WORSHIP-00',
  'SOUTHERN-GOSPEL-00',
  'TRADITIONAL-GOSPEL-00',
  'CLASSICAL-00',
  'ART-SONG-00',
  'AVANT-GARDE-00',
  'BAROQUE-00',
  'BRASS-WOODWINDS-00',
  'CANTATA-00',
  'CELLO-00',
  'CHAMBER-MUSIC-00',
  'CHANT-00',
  'CHORAL-00',
  'CLASSICAL-CROSSOVER-00',
  'HIGH-CLASSICAL-00',
  'CONTEMPORARY-ERA-00',
  'ELECTRONIC-01',
  'GUITAR-00',
  'IMPRESSIONIST-00',
  'MEDIEVAL-00',
  'MINIMALISM-00',
  'MODERN-COMPOSITION-00',
  'OPERA-00',
  'ORATORIO-00',
  'ORCHESTRAL-00',
  'PERCUSSION-00',
  'PIANO-00',
  'RENAISSANCE-00',
  'ROMANTIC-00',
  'SACRED-00',
  'SOLO-INSTRUMENTAL-00',
  'VIOLIN-00',
  'COMEDY-00',
  'NOVELTY-00',
  'STANDUP-COMEDY-00',
  'COUNTRY-00',
  'ALTERNATIVE-COUNTRY-00',
  'AMERICANA-00',
  'BLUEGRASS-00',
  'CONTEMPORARY-BLUEGRASS-00',
  'CONTEMPORARY-COUNTRY-00',
  'COUNTRY-GOSPEL-00',
  'HONKY-TONK-00',
  'OUTLAW-COUNTRY-00',
  'THAI-COUNTRY-00',
  'TRADITIONAL-BLUEGRASS-00',
  'TRADITIONAL-COUNTRY-00',
  'URBAN-COWBOY-00',
  'DANCE-00',
  'BREAKBEAT-00',
  'GARAGE-00',
  'HARDCORE-00',
  'HOUSE-00',
  'JUNGLE-DRUM-N-BASS-00',
  'TECHNO-00',
  'TRANCE-00',
  'DISNEY-00',
  'EASY-LISTENING-00',
  'LOUNGE-00',
  'SWING-00',
  'ELECTRONIC-00',
  'AMBIENT-00',
  'BASS-00',
  'DOWNTEMPO-00',
  'DUBSTEP-00',
  'ELECTRONICA-00',
  'IDM-EXPERIMENTAL-00',
  'INDUSTRIAL-00',
  'ENKA-00',
  'FITNESS-WORKOUT-00',
  'FOLK-00',
  'FRENCH-POP-00',
  'GERMAN-FOLK-00',
  'GERMAN-POP-00',
  'HIP-HOP-RAP-00',
  'ALTERNATIVE-RAP-00',
  'CHINESE-HIP-HOP-00',
  'DIRTY-SOUTH-00',
  'EAST-COAST-RAP-00',
  'GANGSTA-RAP-00',
  'HARDCORE-RAP-00',
  'HIP-HOP-00',
  'KOREAN-HIP-HOP-00',
  'LATIN-RAP-00',
  'OLD-SCHOOL-RAP-00',
  'RAP-00',
  'UK-HIP-HOP-00',
  'UNDERGROUND-RAP-00',
  'WEST-COAST-RAP-00',
  'HOLIDAY-00',
  'CHANUKAH-00',
  'CHRISTMAS-00',
  'CHRISTMAS-CHILDRENS-00',
  'CHRISTMAS-CLASSIC-00',
  'CHRISTMAS-CLASSICAL-00',
  'CHRISTMAS-JAZZ-00',
  'CHRISTMAS-MODERN-00',
  'CHRISTMAS-POP-00',
  'CHRISTMAS-R-B-00',
  'CHRISTMAS-RELIGIOUS-00',
  'CHRISTMAS-ROCK-00',
  'EASTER-00',
  'HALLOWEEN-00',
  'THANKSGIVING-00',
  'INDIAN-00',
  'BOLLYWOOD-00',
  'DEVOTIONAL-SPIRITUAL-00',
  'GHAZALS-00',
  'INDIAN-CLASSICAL-00',
  'INDIAN-FOLK-00',
  'INDIAN-POP-00',
  'REGIONAL-INDIAN-00',
  'SUFI-AND-GHAZALS-00',
  'TAMIL-00',
  'TELUGU-00',
  'INSPIRATIONAL-00',
  'INSTRUMENTAL-00',
  'J-POP-00',
  'JAZZ-00',
  'AVANT-GARDE-JAZZ-00',
  'BOP-00',
  'BIG-BAND-00',
  'CONTEMPORARY-JAZZ-00',
  'COOL-00',
  'CROSSOVER-JAZZ-00',
  'DIXIELAND-00',
  'FUSION-00',
  'HARD-BOP-00',
  'LATIN-JAZZ-00',
  'MAINSTREAM-JAZZ-00',
  'RAGTIME-00',
  'SMOOTH-JAZZ-00',
  'TRAD-JAZZ-00',
  'VOCAL-JAZZ-00',
  'KARAOKE-00',
  'KAYOKYOKU-00',
  'KOREAN-00',
  'KOREAN-CLASSICAL-00',
  'LATIN-00',
  'ALTERNATIVO-ROCK-LATINO-00',
  'BALADAS-Y-BOLEROS-00',
  'CONTEMPORARY-LATIN-00',
  'LATIN-JAZZ-01',
  'REGGAETON-Y-HIP-HOP-00',
  'POP-LATINO-00',
  'RAICES-00',
  'REGIONAL-MEXICANO-00',
  'SALSA-Y-TROPICAL-00',
  'MARCHING-BANDS-00',
  'NEW-AGE-00',
  'HEALING-00',
  'MEDITATION-00',
  'NATURE-00',
  'RELAXATION-00',
  'TRAVEL-00',
  'YOGA-00',
  'POP-00',
  'ADULT-CONTEMPORARY-00',
  'BRITPOP-00',
  'CANTOPOP-HK-POP-00',
  'INDO-POP-00',
  'K-POP-00',
  'KOREAN-FOLK-POP-00',
  'MALAYSIAN-POP-00',
  'MANDOPOP-00',
  'MANILLA-SOUND-00',
  'OLDIES-00',
  'ORIGINAL-PILIPINO-MUSIC-00',
  'PINOY-POP-00',
  'POP-ROCK-00',
  'SOFT-ROCK-00',
  'TAI-POP-00',
  'TEEN-POP-00',
  'THAI-POP-00',
  'R-B-SOUL-00',
  'CONTEMPORARY-R-B-00',
  'DISCO-00',
  'DOO-WOP-00',
  'FUNK-00',
  'MOTOWN-00',
  'NEO-SOUL-00',
  'SOUL-00',
  'REGGAE-00',
  'DUB-00',
  'LOVERS-ROCK-00',
  'DANCEHALL-00',
  'ROOTS-REGGAE-00',
  'SKA-00',
  'ROCK-00',
  'ADULT-ALTERNATIVE-00',
  'AMERICAN-TRAD-ROCK-00',
  'ARENA-ROCK-00',
  'BLUES-ROCK-00',
  'BRITISH-INVASION-00',
  'CHINESE-ROCK-00',
  'DEATH-METAL-BLACK-METAL-00',
  'GLAM-ROCK-00',
  'HAIR-METAL-00',
  'HARD-ROCK-00',
  'HEAVY-METAL-00',
  'JAM-BANDS-00',
  'KOREAN-ROCK-00',
  'PROG-ROCK-ART-ROCK-00',
  'PSYCHEDELIC-00',
  'ROCK-ROLL-00',
  'ROCKABILLY-00',
  'ROOTS-ROCK-00',
  'SINGER-SONGWRITER-01',
  'SOUTHERN-ROCK-00',
  'SURF-00',
  'TEX-MEX-00',
  'SINGER-SONGWRITER-00',
  'ALTERNATIVE-FOLK-00',
  'CONTEMPORARY-FOLK-00',
  'CONTEMPORARY-SINGER-SONGWRITER-00',
  'FOLK-ROCK-00',
  'NEW-ACOUSTIC-00',
  'TRADITIONAL-FOLK-00',
  'SOUNDTRACK-00',
  'FOREIGN-CINEMA-00',
  'MUSICALS-00',
  'ORIGINAL-SCORE-00',
  'SOUND-EFFECT-00',
  'FILM-SOUNDTRACK-00',
  'TV-SOUNDTRACK-00',
  'SPOKEN-WORD-00',
  'VOCAL-00',
  'STANDARDS-00',
  'TRADITIONAL-POP-00',
  'TROT-00',
  'VOCAL-POP-00',
  'WORLD-00',
  'AFRICA-00',
  'AFRIKAANS-00',
  'AFRO-BEAT-00',
  'AFRO-POP-00',
  'ARABESQUE-00',
  'ASIA-00',
  'AUSTRALIA-00',
  'CAJUN-00',
  'CALYPSO-00',
  'CARIBBEAN-00',
  'CELTIC-00',
  'CELTIC-FOLK-00',
  'CONTEMPORARY-CELTIC-00',
  'DANGDUT-00',
  'DINI-00',
  'EUROPE-00',
  'FADO-00',
  'FARSI-00',
  'FLAMENCO-00',
  'FRANCE-00',
  'HALK-00',
  'HAWAII-00',
  'IBERIA-00',
  'INDONESIAN-RELIGIOUS-00',
  'ISRAELI-00',
  'JAPAN-00',
  'KLEZMER-00',
  'NORTH-AMERICA-00',
  'POLKA-00',
  'RUSSIAN-00',
  'RUSSIAN-CHANSON-00',
  'SANAT-00',
  'SOCA-00',
  'SOUTH-AFRICA-00',
  'SOUTH-AMERICA-00',
  'TANGO-00',
  'TRADITIONAL-CELTIC-00',
  'TURKISH-00',
  'WORLDBEAT-00',
  'ZYDECO-00'
]

const ringtoneGenrePaths = [
  'Ringtones',
  'Ringtones|Alternative',
  'Ringtones|Alternative|Chinese Alt',
  'Ringtones|Alternative|College Rock',
  'Ringtones|Alternative|EMO',
  'Ringtones|Alternative|Goth Rock',
  'Ringtones|Alternative|Grunge',
  'Ringtones|Alternative|Indie Pop',
  'Ringtones|Alternative|Indie Rock',
  'Ringtones|Alternative|Korean Indie',
  'Ringtones|Alternative|New Wave',
  'Ringtones|Alternative|Pop Punk',
  'Ringtones|Alternative|Punk',
  'Ringtones|Anime',
  'Ringtones|Arabic',
  'Ringtones|Arabic|Arabic Pop',
  'Ringtones|Arabic|Islamic',
  'Ringtones|Arabic|Khaleeji',
  'Ringtones|Arabic|North African',
  'Ringtones|Blues',
  'Ringtones|Blues|Acoustic Blues',
  'Ringtones|Blues|Chicago Blues',
  'Ringtones|Blues|Classic Blues',
  'Ringtones|Blues|Contemporary Blues',
  'Ringtones|Blues|Country Blues',
  'Ringtones|Blues|Delta Blues',
  'Ringtones|Blues|Electric Blues',
  'Ringtones|Brazilian',
  'Ringtones|Brazilian|Axé',
  'Ringtones|Brazilian|Baile Funk',
  'Ringtones|Brazilian|Bossa Nova',
  'Ringtones|Brazilian|Choro',
  'Ringtones|Brazilian|Forró',
  'Ringtones|Brazilian|Frevo',
  'Ringtones|Brazilian|MPB',
  'Ringtones|Brazilian|Pagode',
  'Ringtones|Brazilian|Samba',
  'Ringtones|Brazilian|Sertanejo',
  "Ringtones|Children's Music",
  "Ringtones|Children's Music|Lullabies",
  "Ringtones|Children's Music|Sing-Along",
  "Ringtones|Children's Music|Stories",
  'Ringtones|Chinese',
  'Ringtones|Chinese|Chinese Classical',
  'Ringtones|Chinese|Chinese Flute',
  'Ringtones|Chinese|Chinese Opera',
  'Ringtones|Chinese|Chinese Orchestral',
  'Ringtones|Chinese|Chinese Regional Folk',
  'Ringtones|Chinese|Chinese Strings',
  'Ringtones|Chinese|Taiwanese Folk',
  'Ringtones|Chinese|Tibetan Native Music',
  'Ringtones|Christian & Gospel',
  'Ringtones|Christian & Gospel|CCM',
  'Ringtones|Christian & Gospel|Christian Metal',
  'Ringtones|Christian & Gospel|Christian Pop',
  'Ringtones|Christian & Gospel|Christian Rap',
  'Ringtones|Christian & Gospel|Christian Rock',
  'Ringtones|Christian & Gospel|Classic Christian',
  'Ringtones|Christian & Gospel|Contemporary Gospel',
  'Ringtones|Christian & Gospel|Gospel',
  'Ringtones|Christian & Gospel|Praise & Worship',
  'Ringtones|Christian & Gospel|Southern Gospel',
  'Ringtones|Christian & Gospel|Traditional Gospel',
  'Ringtones|Classical',
  'Ringtones|Classical|Art Song',
  'Ringtones|Classical|Avant-Garde',
  'Ringtones|Classical|Baroque Era',
  'Ringtones|Classical|Brass & Woodwinds',
  'Ringtones|Classical|Cantata',
  'Ringtones|Classical|Cello',
  'Ringtones|Classical|Chamber Music',
  'Ringtones|Classical|Chant',
  'Ringtones|Classical|Choral',
  'Ringtones|Classical|Classical Crossover',
  'Ringtones|Classical|Classical Era',
  'Ringtones|Classical|Contemporary Era',
  'Ringtones|Classical|Electronic',
  'Ringtones|Classical|Guitar',
  'Ringtones|Classical|Impressionist',
  'Ringtones|Classical|Medieval Era',
  'Ringtones|Classical|Minimalism',
  'Ringtones|Classical|Modern Era',
  'Ringtones|Classical|Opera',
  'Ringtones|Classical|Oratorio',
  'Ringtones|Classical|Orchestral',
  'Ringtones|Classical|Percussion',
  'Ringtones|Classical|Piano',
  'Ringtones|Classical|Renaissance',
  'Ringtones|Classical|Romantic Era',
  'Ringtones|Classical|Sacred',
  'Ringtones|Classical|Solo Instrumental',
  'Ringtones|Classical|Violin',
  'Ringtones|Comedy',
  'Ringtones|Comedy|Novelty',
  'Ringtones|Comedy|Standup Comedy',
  'Ringtones|Country',
  'Ringtones|Country|Alternative Country',
  'Ringtones|Country|Americana',
  'Ringtones|Country|Bluegrass',
  'Ringtones|Country|Contemporary Bluegrass',
  'Ringtones|Country|Contemporary Country',
  'Ringtones|Country|Country Gospel',
  'Ringtones|Country|Honky Tonk',
  'Ringtones|Country|Outlaw Country',
  'Ringtones|Country|Thai Country',
  'Ringtones|Country|Traditional Bluegrass',
  'Ringtones|Country|Traditional Country',
  'Ringtones|Country|Urban Cowboy',
  'Ringtones|Dance',
  'Ringtones|Dance|Breakbeat',
  'Ringtones|Dance|Garage',
  'Ringtones|Dance|Hardcore',
  'Ringtones|Dance|House',
  "Ringtones|Dance|Jungle/Drum'n'bass",
  'Ringtones|Dance|Techno',
  'Ringtones|Dance|Trance',
  'Ringtones|Disney',
  'Ringtones|Easy Listening',
  'Ringtones|Easy Listening|Lounge',
  'Ringtones|Easy Listening|Swing',
  'Ringtones|Electronic',
  'Ringtones|Electronic|Ambient',
  'Ringtones|Electronic|Bass',
  'Ringtones|Electronic|Downtempo',
  'Ringtones|Electronic|Dubstep',
  'Ringtones|Electronic|Electronica',
  'Ringtones|Electronic|IDM/Experimental',
  'Ringtones|Electronic|Industrial',
  'Ringtones|Enka',
  'Ringtones|Fitness & Workout',
  'Ringtones|Folk',
  'Ringtones|French Pop',
  'Ringtones|German Folk',
  'Ringtones|German Pop',
  'Ringtones|Hip Hop/Rap',
  'Ringtones|Hip Hop/Rap|Alternative Rap',
  'Ringtones|Hip Hop/Rap|Chinese Hip-Hop',
  'Ringtones|Hip Hop/Rap|Dirty South',
  'Ringtones|Hip Hop/Rap|East Coast Rap',
  'Ringtones|Hip Hop/Rap|Gangsta Rap',
  'Ringtones|Hip Hop/Rap|Hardcore Rap',
  'Ringtones|Hip Hop/Rap|Hip-Hop',
  'Ringtones|Hip Hop/Rap|Korean Hip-Hop',
  'Ringtones|Hip Hop/Rap|Latin Rap',
  'Ringtones|Hip Hop/Rap|Old School Rap',
  'Ringtones|Hip Hop/Rap|Rap',
  'Ringtones|Hip Hop/Rap|UK Hip Hop',
  'Ringtones|Hip Hop/Rap|Underground Rap',
  'Ringtones|Hip Hop/Rap|West Coast Rap',
  'Ringtones|Holiday',
  'Ringtones|Holiday|Chanukah',
  'Ringtones|Holiday|Christmas',
  "Ringtones|Holiday|Christmas: Children's",
  'Ringtones|Holiday|Christmas: Classic',
  'Ringtones|Holiday|Christmas: Classical',
  'Ringtones|Holiday|Christmas: Jazz',
  'Ringtones|Holiday|Christmas: Modern',
  'Ringtones|Holiday|Christmas: Pop',
  'Ringtones|Holiday|Christmas: R&B',
  'Ringtones|Holiday|Christmas: Religious',
  'Ringtones|Holiday|Christmas: Rock',
  'Ringtones|Holiday|Easter',
  'Ringtones|Holiday|Halloween',
  'Ringtones|Holiday|Thanksgiving',
  'Ringtones|Indian',
  'Ringtones|Indian|Bollywood',
  'Ringtones|Indian|Devotional & Spiritual',
  'Ringtones|Indian|Ghazals',
  'Ringtones|Indian|Indian Classical',
  'Ringtones|Indian|Indian Folk',
  'Ringtones|Indian|Indian Pop',
  'Ringtones|Indian|Regional Indian',
  'Ringtones|Indian|Sufi',
  'Ringtones|Indian|Tamil',
  'Ringtones|Indian|Telugu',
  'Ringtones|Inspirational',
  'Ringtones|Instrumental',
  'Ringtones|J-Pop',
  'Ringtones|Jazz',
  'Ringtones|Jazz|Avant-Garde Jazz',
  'Ringtones|Jazz|Bebop',
  'Ringtones|Jazz|Big Band',
  'Ringtones|Jazz|Contemporary Jazz',
  'Ringtones|Jazz|Cool',
  'Ringtones|Jazz|Crossover Jazz',
  'Ringtones|Jazz|Dixieland',
  'Ringtones|Jazz|Fusion',
  'Ringtones|Jazz|Hard Bop',
  'Ringtones|Jazz|Latin Jazz',
  'Ringtones|Jazz|Mainstream Jazz',
  'Ringtones|Jazz|Ragtime',
  'Ringtones|Jazz|Smooth Jazz',
  'Ringtones|Jazz|Trad Jazz',
  'Ringtones|Jazz|Vocal Jazz',
  'Ringtones|Karaoke',
  'Ringtones|Kayokyoku',
  'Ringtones|Korean',
  'Ringtones|Korean|Korean Traditional',
  'Ringtones|Latin',
  'Ringtones|Latin|Alternative & Rock in Spanish',
  'Ringtones|Latin|Baladas y Boleros',
  'Ringtones|Latin|Contemporary Latin',
  'Ringtones|Latin|Latin Jazz',
  'Ringtones|Latin|Latin Urban',
  'Ringtones|Latin|Pop in Spanish',
  'Ringtones|Latin|Raices',
  'Ringtones|Latin|Regional Mexicano',
  'Ringtones|Latin|Salsa y Tropical',
  'Ringtones|Marching Bands',
  'Ringtones|New Age',
  'Ringtones|New Age|Healing',
  'Ringtones|New Age|Meditation',
  'Ringtones|New Age|Nature',
  'Ringtones|New Age|Relaxation',
  'Ringtones|New Age|Travel',
  'Ringtones|New Age|Yoga',
  'Ringtones|Pop',
  'Ringtones|Pop|Adult Contemporary',
  'Ringtones|Pop|Britpop',
  'Ringtones|Pop|Cantopop',
  'Ringtones|Pop|Indo Pop',
  'Ringtones|Pop|K-Pop',
  'Ringtones|Pop|Korean Folk-Pop',
  'Ringtones|Pop|Malaysian Pop',
  'Ringtones|Pop|Mandopop',
  'Ringtones|Pop|Manilla Sound',
  'Ringtones|Pop|Oldies',
  'Ringtones|Pop|Original Pilipino Music',
  'Ringtones|Pop|Pinoy Pop',
  'Ringtones|Pop|Pop/Rock',
  'Ringtones|Pop|Soft Rock',
  'Ringtones|Pop|Tai-Pop',
  'Ringtones|Pop|Teen Pop',
  'Ringtones|Pop|Thai Pop',
  'Ringtones|R&B/Soul',
  'Ringtones|R&B/Soul|Contemporary R&B',
  'Ringtones|R&B/Soul|Disco',
  'Ringtones|R&B/Soul|Doo Wop',
  'Ringtones|R&B/Soul|Funk',
  'Ringtones|R&B/Soul|Motown',
  'Ringtones|R&B/Soul|Neo-Soul',
  'Ringtones|R&B/Soul|Soul',
  'Ringtones|Reggae',
  'Ringtones|Reggae|Dub',
  'Ringtones|Reggae|Lovers Rock',
  'Ringtones|Reggae|Modern Dancehall',
  'Ringtones|Reggae|Roots Reggae',
  'Ringtones|Reggae|Ska',
  'Ringtones|Rock',
  'Ringtones|Rock|Adult Alternative',
  'Ringtones|Rock|American Trad Rock',
  'Ringtones|Rock|Arena Rock',
  'Ringtones|Rock|Blues-Rock',
  'Ringtones|Rock|British Invasion',
  'Ringtones|Rock|Chinese Rock',
  'Ringtones|Rock|Death Metal/Black Metal',
  'Ringtones|Rock|Glam Rock',
  'Ringtones|Rock|Hair Metal',
  'Ringtones|Rock|Hard Rock',
  'Ringtones|Rock|Heavy Metal',
  'Ringtones|Rock|Jam Bands',
  'Ringtones|Rock|Korean Rock',
  'Ringtones|Rock|Prog-Rock/Art Rock',
  'Ringtones|Rock|Psychedelic',
  'Ringtones|Rock|Rock & Roll',
  'Ringtones|Rock|Rockabilly',
  'Ringtones|Rock|Roots Rock',
  'Ringtones|Rock|Singer/Songwriter',
  'Ringtones|Rock|Southern Rock',
  'Ringtones|Rock|Surf',
  'Ringtones|Rock|Tex-Mex',
  'Ringtones|Singer/Songwriter',
  'Ringtones|Singer/Songwriter|Alternative Folk',
  'Ringtones|Singer/Songwriter|Contemporary Folk',
  'Ringtones|Singer/Songwriter|Contemporary Singer/Songwriter',
  'Ringtones|Singer/Songwriter|Folk-Rock',
  'Ringtones|Singer/Songwriter|New Acoustic',
  'Ringtones|Singer/Songwriter|Traditional Folk',
  'Ringtones|Soundtrack',
  'Ringtones|Soundtrack|Foreign Cinema',
  'Ringtones|Soundtrack|Musicals',
  'Ringtones|Soundtrack|Original Score',
  'Ringtones|Soundtrack|Sound Effects',
  'Ringtones|Soundtrack|Soundtrack',
  'Ringtones|Soundtrack|TV Soundtrack',
  'Ringtones|Spoken Word',
  'Ringtones|Vocal',
  'Ringtones|Vocal|Standards',
  'Ringtones|Vocal|Traditional Pop',
  'Ringtones|Vocal|Trot',
  'Ringtones|Vocal|Vocal Pop',
  'Ringtones|World',
  'Ringtones|World|Africa',
  'Ringtones|World|Afrikaans',
  'Ringtones|World|Afro-Beat',
  'Ringtones|World|Afro-Pop',
  'Ringtones|World|Arabesque',
  'Ringtones|World|Asia',
  'Ringtones|World|Australia',
  'Ringtones|World|Cajun',
  'Ringtones|World|Calypso',
  'Ringtones|World|Caribbean',
  'Ringtones|World|Celtic',
  'Ringtones|World|Celtic Folk',
  'Ringtones|World|Contemporary Celtic',
  'Ringtones|World|Dangdut',
  'Ringtones|World|Dini',
  'Ringtones|World|Europe',
  'Ringtones|World|Fado',
  'Ringtones|World|Farsi',
  'Ringtones|World|Flamenco',
  'Ringtones|World|France',
  'Ringtones|World|Halk',
  'Ringtones|World|Hawaii',
  'Ringtones|World|Iberia',
  'Ringtones|World|Indonesian Religious',
  'Ringtones|World|Israeli',
  'Ringtones|World|Japan',
  'Ringtones|World|Klezmer',
  'Ringtones|World|North America',
  'Ringtones|World|Polka',
  'Ringtones|World|Russian',
  'Ringtones|World|Russian Chanson',
  'Ringtones|World|Sanat',
  'Ringtones|World|Soca',
  'Ringtones|World|South Africa',
  'Ringtones|World|South America',
  'Ringtones|World|Tango',
  'Ringtones|World|Traditional Celtic',
  'Ringtones|World|Turkish',
  'Ringtones|World|Worldbeat',
  'Ringtones|World|Zydeco'
]

const ringtoneGenreNames = [
  'Ringtones',
  'Alternative',
  'Chinese Alt',
  'College Rock',
  'EMO',
  'Goth Rock',
  'Grunge',
  'Indie Pop',
  'Indie Rock',
  'Korean Indie',
  'New Wave',
  'Pop Punk',
  'Punk',
  'Anime',
  'Arabic',
  'Arabic Pop',
  'Islamic',
  'Khaleeji',
  'North African',
  'Blues',
  'Acoustic Blues',
  'Chicago Blues',
  'Classic Blues',
  'Contemporary Blues',
  'Country Blues',
  'Delta Blues',
  'Electric Blues',
  'Brazilian',
  'Axé',
  'Baile Funk',
  'Bossa Nova',
  'Choro',
  'Forró',
  'Frevo',
  'MPB',
  'Pagode',
  'Samba',
  'Sertanejo',
  "Children's Music",
  'Lullabies',
  'Sing-Along',
  'Stories',
  'Chinese',
  'Chinese Classical',
  'Chinese Flute',
  'Chinese Opera',
  'Chinese Orchestral',
  'Chinese Regional Folk',
  'Chinese Strings',
  'Taiwanese Folk',
  'Tibetan Native Music',
  'Christian & Gospel',
  'CCM',
  'Christian Metal',
  'Christian Pop',
  'Christian Rap',
  'Christian Rock',
  'Classic Christian',
  'Contemporary Gospel',
  'Gospel',
  'Praise & Worship',
  'Southern Gospel',
  'Traditional Gospel',
  'Classical',
  'Art Song',
  'Avant-Garde',
  'Baroque Era',
  'Brass & Woodwinds',
  'Cantata',
  'Cello',
  'Chamber Music',
  'Chant',
  'Choral',
  'Classical Crossover',
  'Classical Era',
  'Contemporary Era',
  'Electronic',
  'Guitar',
  'Impressionist',
  'Medieval Era',
  'Minimalism',
  'Modern Era',
  'Opera',
  'Oratorio',
  'Orchestral',
  'Percussion',
  'Piano',
  'Renaissance',
  'Romantic Era',
  'Sacred',
  'Solo Instrumental',
  'Violin',
  'Comedy',
  'Novelty',
  'Standup Comedy',
  'Country',
  'Alternative Country',
  'Americana',
  'Bluegrass',
  'Contemporary Bluegrass',
  'Contemporary Country',
  'Country Gospel',
  'Honky Tonk',
  'Outlaw Country',
  'Thai Country',
  'Traditional Bluegrass',
  'Traditional Country',
  'Urban Cowboy',
  'Dance',
  'Breakbeat',
  'Garage',
  'Hardcore',
  'House',
  "Jungle/Drum'n'bass",
  'Techno',
  'Trance',
  'Disney',
  'Easy Listening',
  'Lounge',
  'Swing',
  'Electronic',
  'Ambient',
  'Bass',
  'Downtempo',
  'Dubstep',
  'Electronica',
  'IDM/Experimental',
  'Industrial',
  'Enka',
  'Fitness & Workout',
  'Folk',
  'French Pop',
  'German Folk',
  'German Pop',
  'Hip Hop/Rap',
  'Alternative Rap',
  'Chinese Hip-Hop',
  'Dirty South',
  'East Coast Rap',
  'Gangsta Rap',
  'Hardcore Rap',
  'Hip-Hop',
  'Korean Hip-Hop',
  'Latin Rap',
  'Old School Rap',
  'Rap',
  'UK Hip Hop',
  'Underground Rap',
  'West Coast Rap',
  'Holiday',
  'Chanukah',
  'Christmas',
  "Christmas: Children's",
  'Christmas: Classic',
  'Christmas: Classical',
  'Christmas: Jazz',
  'Christmas: Modern',
  'Christmas: Pop',
  'Christmas: R&B',
  'Christmas: Religious',
  'Christmas: Rock',
  'Easter',
  'Halloween',
  'Thanksgiving',
  'Indian',
  'Bollywood',
  'Devotional & Spiritual',
  'Ghazals',
  'Indian Classical',
  'Indian Folk',
  'Indian Pop',
  'Regional Indian',
  'Sufi',
  'Tamil',
  'Telugu',
  'Inspirational',
  'Instrumental',
  'J-Pop',
  'Jazz',
  'Avant-Garde Jazz',
  'Bebop',
  'Big Band',
  'Contemporary Jazz',
  'Cool',
  'Crossover Jazz',
  'Dixieland',
  'Fusion',
  'Hard Bop',
  'Latin Jazz',
  'Mainstream Jazz',
  'Ragtime',
  'Smooth Jazz',
  'Trad Jazz',
  'Vocal Jazz',
  'Karaoke',
  'Kayokyoku',
  'Korean',
  'Korean Traditional',
  'Latin',
  'Alternative & Rock in Spanish',
  'Baladas y Boleros',
  'Contemporary Latin',
  'Latin Jazz',
  'Latin Urban',
  'Pop in Spanish',
  'Raices',
  'Regional Mexicano',
  'Salsa y Tropical',
  'Marching Bands',
  'New Age',
  'Healing',
  'Meditation',
  'Nature',
  'Relaxation',
  'Travel',
  'Yoga',
  'Pop',
  'Adult Contemporary',
  'Britpop',
  'Cantopop',
  'Indo Pop',
  'K-Pop',
  'Korean Folk-Pop',
  'Malaysian Pop',
  'Mandopop',
  'Manilla Sound',
  'Oldies',
  'Original Pilipino Music',
  'Pinoy Pop',
  'Pop/Rock',
  'Soft Rock',
  'Tai-Pop',
  'Teen Pop',
  'Thai Pop',
  'R&B/Soul',
  'Contemporary R&B',
  'Disco',
  'Doo Wop',
  'Funk',
  'Motown',
  'Neo-Soul',
  'Soul',
  'Reggae',
  'Dub',
  'Lovers Rock',
  'Modern Dancehall',
  'Roots Reggae',
  'Ska',
  'Rock',
  'Adult Alternative',
  'American Trad Rock',
  'Arena Rock',
  'Blues-Rock',
  'British Invasion',
  'Chinese Rock',
  'Death Metal/Black Metal',
  'Glam Rock',
  'Hair Metal',
  'Hard Rock',
  'Heavy Metal',
  'Jam Bands',
  'Korean Rock',
  'Prog-Rock/Art Rock',
  'Psychedelic',
  'Rock & Roll',
  'Rockabilly',
  'Roots Rock',
  'Singer/Songwriter',
  'Southern Rock',
  'Surf',
  'Tex-Mex',
  'Singer/Songwriter',
  'Alternative Folk',
  'Contemporary Folk',
  'Contemporary Singer/Songwriter',
  'Folk-Rock',
  'New Acoustic',
  'Traditional Folk',
  'Soundtrack',
  'Foreign Cinema',
  'Musicals',
  'Original Score',
  'Sound Effects',
  'Soundtrack',
  'TV Soundtrack',
  'Spoken Word',
  'Vocal',
  'Standards',
  'Traditional Pop',
  'Trot',
  'Vocal Pop',
  'World',
  'Africa',
  'Afrikaans',
  'Afro-Beat',
  'Afro-Pop',
  'Arabesque',
  'Asia',
  'Australia',
  'Cajun',
  'Calypso',
  'Caribbean',
  'Celtic',
  'Celtic Folk',
  'Contemporary Celtic',
  'Dangdut',
  'Dini',
  'Europe',
  'Fado',
  'Farsi',
  'Flamenco',
  'France',
  'Halk',
  'Hawaii',
  'Iberia',
  'Indonesian Religious',
  'Israeli',
  'Japan',
  'Klezmer',
  'North America',
  'Polka',
  'Russian',
  'Russian Chanson',
  'Sanat',
  'Soca',
  'South Africa',
  'South America',
  'Tango',
  'Traditional Celtic',
  'Turkish',
  'Worldbeat',
  'Zydeco'
]

const ringtoneGenreCodes = [
  'RINGTONES-00',
  'ALTERNATIVE-00',
  'CHINESE-ALT-00',
  'COLLEGE-ROCK-00',
  'EMO-00',
  'GOTH-ROCK-00',
  'GRUNGE-00',
  'INDIE-POP-00',
  'INDIE-ROCK-00',
  'KOREAN-INDIE-00',
  'NEW-WAVE-00',
  'POP-PUNK-00',
  'PUNK-00',
  'ANIME-00',
  'MIDDLE-EAST-00',
  'ARABIC-POP-00',
  'ISLAMIC-00',
  'KHALEEJI-00',
  'NORTH-AFRICAN-00',
  'BLUES-00',
  'ACOUSTIC-BLUES-00',
  'CHICAGO-BLUES-00',
  'CLASSIC-BLUES-00',
  'CONTEMPORARY-BLUES-00',
  'COUNTRY-BLUES-00',
  'DELTA-BLUES-00',
  'ELECTRIC-BLUES-00',
  'BRAZILIAN-00',
  'AXE-00',
  'BAILE-FUNK-00',
  'BOSSA-NOVA-00',
  'CHORO-00',
  'FORRO-00',
  'FREVO-00',
  'MPB-00',
  'PAGODE-00',
  'SAMBA-00',
  'SERTANEJO-00',
  'CHILDREN-MUSIC-00',
  'LULLABIES-00',
  'SING-ALONG-00',
  'STORIES-00',
  'CHINESE-00',
  'CHINESE-CLASSICAL-00',
  'CHINESE-FLUTE-00',
  'CHINESE-OPERA-00',
  'CHINESE-ORCHESTRAL-00',
  'CHINESE-REGIONAL-FOLK-00',
  'CHINESE-STRINGS-00',
  'TAIWANESE-FOLK-00',
  'TIBETAN-NATIVE-MUSIC-00',
  'CHRISTIAN-GOSPEL-00',
  'CCM-00',
  'CHRISTIAN-METAL-00',
  'CHRISTIAN-POP-00',
  'CHRISTIAN-RAP-00',
  'CHRISTIAN-ROCK-00',
  'CLASSIC-CHRISTIAN-00',
  'CONTEMPORARY-GOSPEL-00',
  'GOSPEL-00',
  'PRAISE-WORSHIP-00',
  'SOUTHERN-GOSPEL-00',
  'TRADITIONAL-GOSPEL-00',
  'CLASSICAL-00',
  'ART-SONG-00',
  'AVANT-GARDE-00',
  'BAROQUE-00',
  'BRASS-WOODWINDS-00',
  'CANTATA-00',
  'CELLO-00',
  'CHAMBER-MUSIC-00',
  'CHANT-00',
  'CHORAL-00',
  'CLASSICAL-CROSSOVER-00',
  'HIGH-CLASSICAL-00',
  'CONTEMPORARY-ERA-00',
  'ELECTRONIC-01',
  'GUITAR-00',
  'IMPRESSIONIST-00',
  'MEDIEVAL-00',
  'MINIMALISM-00',
  'MODERN-COMPOSITION-00',
  'OPERA-00',
  'ORATORIO-00',
  'ORCHESTRAL-00',
  'PERCUSSION-00',
  'PIANO-00',
  'RENAISSANCE-00',
  'ROMANTIC-00',
  'SACRED-00',
  'SOLO-INSTRUMENTAL-00',
  'VIOLIN-00',
  'COMEDY-00',
  'NOVELTY-00',
  'STANDUP-COMEDY-00',
  'COUNTRY-00',
  'ALTERNATIVE-COUNTRY-00',
  'AMERICANA-00',
  'BLUEGRASS-00',
  'CONTEMPORARY-BLUEGRASS-00',
  'CONTEMPORARY-COUNTRY-00',
  'COUNTRY-GOSPEL-00',
  'HONKY-TONK-00',
  'OUTLAW-COUNTRY-00',
  'THAI-COUNTRY-00',
  'TRADITIONAL-BLUEGRASS-00',
  'TRADITIONAL-COUNTRY-00',
  'URBAN-COWBOY-00',
  'DANCE-00',
  'BREAKBEAT-00',
  'GARAGE-00',
  'HARDCORE-00',
  'HOUSE-00',
  'JUNGLE-DRUM-N-BASS-00',
  'TECHNO-00',
  'TRANCE-00',
  'DISNEY-00',
  'EASY-LISTENING-00',
  'LOUNGE-00',
  'SWING-00',
  'ELECTRONIC-00',
  'AMBIENT-00',
  'BASS-00',
  'DOWNTEMPO-00',
  'DUBSTEP-00',
  'ELECTRONICA-00',
  'IDM-EXPERIMENTAL-00',
  'INDUSTRIAL-00',
  'ENKA-00',
  'FITNESS-WORKOUT-00',
  'FOLK-00',
  'FRENCH-POP-00',
  'GERMAN-FOLK-00',
  'GERMAN-POP-00',
  'HIP-HOP-RAP-00',
  'ALTERNATIVE-RAP-00',
  'CHINESE-HIP-HOP-00',
  'DIRTY-SOUTH-00',
  'EAST-COAST-RAP-00',
  'GANGSTA-RAP-00',
  'HARDCORE-RAP-00',
  'HIP-HOP-00',
  'KOREAN-HIP-HOP-00',
  'LATIN-RAP-00',
  'OLD-SCHOOL-RAP-00',
  'RAP-00',
  'UK-HIP-HOP-00',
  'UNDERGROUND-RAP-00',
  'WEST-COAST-RAP-00',
  'HOLIDAY-00',
  'CHANUKAH-00',
  'CHRISTMAS-00',
  'CHRISTMAS-CHILDRENS-00',
  'CHRISTMAS-CLASSIC-00',
  'CHRISTMAS-CLASSICAL-00',
  'CHRISTMAS-JAZZ-00',
  'CHRISTMAS-MODERN-00',
  'CHRISTMAS-POP-00',
  'CHRISTMAS-R-B-00',
  'CHRISTMAS-RELIGIOUS-00',
  'CHRISTMAS-ROCK-00',
  'EASTER-00',
  'HALLOWEEN-00',
  'THANKSGIVING-00',
  'INDIAN-00',
  'BOLLYWOOD-00',
  'DEVOTIONAL-SPIRITUAL-00',
  'GHAZALS-00',
  'INDIAN-CLASSICAL-00',
  'INDIAN-FOLK-00',
  'INDIAN-POP-00',
  'REGIONAL-INDIAN-00',
  'SUFI-AND-GHAZALS-00',
  'TAMIL-00',
  'TELUGU-00',
  'INSPIRATIONAL-00',
  'INSTRUMENTAL-00',
  'J-POP-00',
  'JAZZ-00',
  'AVANT-GARDE-JAZZ-00',
  'BOP-00',
  'BIG-BAND-00',
  'CONTEMPORARY-JAZZ-00',
  'COOL-00',
  'CROSSOVER-JAZZ-00',
  'DIXIELAND-00',
  'FUSION-00',
  'HARD-BOP-00',
  'LATIN-JAZZ-00',
  'MAINSTREAM-JAZZ-00',
  'RAGTIME-00',
  'SMOOTH-JAZZ-00',
  'TRAD-JAZZ-00',
  'VOCAL-JAZZ-00',
  'KARAOKE-00',
  'KAYOKYOKU-00',
  'KOREAN-00',
  'KOREAN-CLASSICAL-00',
  'LATIN-00',
  'ALTERNATIVO-ROCK-LATINO-00',
  'BALADAS-Y-BOLEROS-00',
  'CONTEMPORARY-LATIN-00',
  'LATIN-JAZZ-01',
  'REGGAETON-Y-HIP-HOP-00',
  'POP-LATINO-00',
  'RAICES-00',
  'REGIONAL-MEXICANO-00',
  'SALSA-Y-TROPICAL-00',
  'MARCHING-BANDS-00',
  'NEW-AGE-00',
  'HEALING-00',
  'MEDITATION-00',
  'NATURE-00',
  'RELAXATION-00',
  'TRAVEL-00',
  'YOGA-00',
  'POP-00',
  'ADULT-CONTEMPORARY-00',
  'BRITPOP-00',
  'CANTOPOP-HK-POP-00',
  'INDO-POP-00',
  'K-POP-00',
  'KOREAN-FOLK-POP-00',
  'MALAYSIAN-POP-00',
  'MANDOPOP-00',
  'MANILLA-SOUND-00',
  'OLDIES-00',
  'ORIGINAL-PILIPINO-MUSIC-00',
  'PINOY-POP-00',
  'POP-ROCK-00',
  'SOFT-ROCK-00',
  'TAI-POP-00',
  'TEEN-POP-00',
  'THAI-POP-00',
  'R-B-SOUL-00',
  'CONTEMPORARY-R-B-00',
  'DISCO-00',
  'DOO-WOP-00',
  'FUNK-00',
  'MOTOWN-00',
  'NEO-SOUL-00',
  'SOUL-00',
  'REGGAE-00',
  'DUB-00',
  'LOVERS-ROCK-00',
  'DANCEHALL-00',
  'ROOTS-REGGAE-00',
  'SKA-00',
  'ROCK-00',
  'ADULT-ALTERNATIVE-00',
  'AMERICAN-TRAD-ROCK-00',
  'ARENA-ROCK-00',
  'BLUES-ROCK-00',
  'BRITISH-INVASION-00',
  'CHINESE-ROCK-00',
  'DEATH-METAL-BLACK-METAL-00',
  'GLAM-ROCK-00',
  'HAIR-METAL-00',
  'HARD-ROCK-00',
  'HEAVY-METAL-00',
  'JAM-BANDS-00',
  'KOREAN-ROCK-00',
  'PROG-ROCK-ART-ROCK-00',
  'PSYCHEDELIC-00',
  'ROCK-ROLL-00',
  'ROCKABILLY-00',
  'ROOTS-ROCK-00',
  'SINGER-SONGWRITER-01',
  'SOUTHERN-ROCK-00',
  'SURF-00',
  'TEX-MEX-00',
  'SINGER-SONGWRITER-00',
  'ALTERNATIVE-FOLK-00',
  'CONTEMPORARY-FOLK-00',
  'CONTEMPORARY-SINGER-SONGWRITER-00',
  'FOLK-ROCK-00',
  'NEW-ACOUSTIC-00',
  'TRADITIONAL-FOLK-00',
  'SOUNDTRACK-00',
  'FOREIGN-CINEMA-00',
  'MUSICALS-00',
  'ORIGINAL-SCORE-00',
  'SOUND-EFFECT-00',
  'FILM-SOUNDTRACK-00',
  'TV-SOUNDTRACK-00',
  'SPOKEN-WORD-00',
  'VOCAL-00',
  'STANDARDS-00',
  'TRADITIONAL-POP-00',
  'TROT-00',
  'VOCAL-POP-00',
  'WORLD-00',
  'AFRICA-00',
  'AFRIKAANS-00',
  'AFRO-BEAT-00',
  'AFRO-POP-00',
  'ARABESQUE-00',
  'ASIA-00',
  'AUSTRALIA-00',
  'CAJUN-00',
  'CALYPSO-00',
  'CARIBBEAN-00',
  'CELTIC-00',
  'CELTIC-FOLK-00',
  'CONTEMPORARY-CELTIC-00',
  'DANGDUT-00',
  'DINI-00',
  'EUROPE-00',
  'FADO-00',
  'FARSI-00',
  'FLAMENCO-00',
  'FRANCE-00',
  'HALK-00',
  'HAWAII-00',
  'IBERIA-00',
  'INDONESIAN-RELIGIOUS-00',
  'ISRAELI-00',
  'JAPAN-00',
  'KLEZMER-00',
  'NORTH-AMERICA-00',
  'POLKA-00',
  'RUSSIAN-00',
  'RUSSIAN-CHANSON-00',
  'SANAT-00',
  'SOCA-00',
  'SOUTH-AFRICA-00',
  'SOUTH-AMERICA-00',
  'TANGO-00',
  'TRADITIONAL-CELTIC-00',
  'TURKISH-00',
  'WORLDBEAT-00',
  'ZYDECO-00'
]

module.exports = {
  'DATABASE': (() => {
    if (config.util.getEnv('NODE_ENV') === 'test') {
      return 'analysis-lib-test'
    }

    return 'analysis-lib'
  })(),
  'REPORTS-DIR': ['.', 'src', 'reports'],
  GENRE: {
    MUSIC: {
      PATHS: musicGenrePaths,
      NAMES: musicGenreNames,
      CODES: musicGenreCodes
    },
    MUSIC_VIDEO: {
      PATHS: musicVideoGenrePaths,
      NAMES: musicVideoGenreNames,
      CODES: musicVideoGenreCodes
    },
    RINGTONE: {
      PATHS: ringtoneGenrePaths,
      NAMES: ringtoneGenreNames,
      CODES: ringtoneGenreCodes
    }
  }
}
