export const SUBMISSIONS = 'SUBMISSIONS' // SUCCESS
export const SUBMISSIONS_REQUEST = 'SUBMISSIONS_REQUEST' // REQUEST ON
export const SUBMISSIONS_FAILURE = 'SUBMISSIONS_FAILURE' // REQUEST FAILES
export const SUBMISSION = 'SUBMISSION' // SUBMISSION OBJECT
export const SUBMISSION_TSV = 'SUBMISSION_TSV'
export const SUBMISSIONS_ADD = 'SUBMISSIONS_ADD'
export const SUBMISSIONS_LOADED = 'SUBMISSIONS_LOADED'
export const SUBMISSION_ERRORS = 'SUBMISSION_ERRORS'
export const FIELDS = 'FIELDS'
export const FIELDS_FAILURE = 'FIELDS_FAILURE'
export const FIELDS_REQUEST = 'FIELDS_REQUEST'
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY'
export const SET_ROW_BY_ROW_DATA = 'SET_ROW_BY_ROW_DATA'
export const SET_FIELD_BY_FIELD_DATA = 'SET_FIELD_BY_FIELD_DATA'
export const SET_ERROR_BY_ERROR_DATA = 'SET_ERROR_BY_ERROR_DATA'

export const FILTERS_META = 'FILTERS_META'
export const CONFIG_REQUEST = 'CONFIG_REQUEST'
export const CONFIG_FAILURE = 'CONFIG_FAILURE'
export const ACTIVE_REPORT_CATEGORY = 'ACTIVE_REPORT_CATEGORY'
export const ROW_BY_ROW_REPORT = 'ROW_BY_ROW_REPORT'
export const FIELD_BY_FIELD_REPORT = 'FIELD_BY_FIELD_REPORT'
export const ERROR_BY_ERROR_REPORT = 'ERROR_BY_ERROR_REPORT'
export const ERROR_BY_ERROR_REPORT_FAILURE = 'ERROR_BY_ERROR_REPORT_FAILURE'

export const DATE_FORMAT = 'MM-DD-YYYY. HH:mm'

export const DATASET_COLUMNS = 'DATASET_COLUMNS'
