export const SUBMISSIONS = 'SUBMISSIONS' // SUCCESS
export const SUBMISSIONS_REQUEST = 'SUBMISSIONS_REQUEST' // REQUEST ON
export const SUBMISSIONS_FAILURE = 'SUBMISSIONS_FAILURE' // REQUEST FAILES
export const SUBMISSION = 'SUBMISSION' // SUBMISSION OBJECT
export const SUBMISSIONS_ADD = 'SUBMISSIONS_ADD'
export const FIELDS = 'FIELDS'
export const FIELDS_FAILURE = 'FIELDS_FAILURE'
export const FIELDS_REQUEST = 'FIELDS_REQUEST'
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY'

export const FILTERS_META = 'FILTERS_META'
export const CONFIG_REQUEST = 'CONFIG_REQUEST'
export const CONFIG_FAILURE = 'CONFIG_FAILURE'
export const ACTIVE_REPORT_CATEGORY = 'ACTIVE_REPORT_CATEGORY'