export const SUBMISSIONS = 'SUBMISSIONS'; // SUCCESS
export const SUBMISSIONS_REQUEST = 'SUBMISSIONS_REQUEST'; // REQUEST ON
export const SUBMISSIONS_FAILURE = 'SUBMISSIONS_FAILURE'; // REQUEST FAILES